package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class AppointmentTimeItem{
        
            /**
            *排班时间id
            **/
            public int id ;
            public int getId(){ return this.id; }
            public void setId(int id){ this.id = id; }

            public int id(){ return this.id; }
            public AppointmentTimeItem id(int id){ this.id = id; return this; }
          
            /**
            *医生排班开始时间
            **/
            public long appointmentBeginTime ;
            public long getAppointmentBeginTime(){ return this.appointmentBeginTime; }
            public void setAppointmentBeginTime(long appointmentBeginTime){ this.appointmentBeginTime = appointmentBeginTime; }

            public long appointmentBeginTime(){ return this.appointmentBeginTime; }
            public AppointmentTimeItem appointmentBeginTime(long appointmentBeginTime){ this.appointmentBeginTime = appointmentBeginTime; return this; }
          
            /**
            *医生排班结束时间
            **/
            public long appointmentEndTime ;
            public long getAppointmentEndTime(){ return this.appointmentEndTime; }
            public void setAppointmentEndTime(long appointmentEndTime){ this.appointmentEndTime = appointmentEndTime; }

            public long appointmentEndTime(){ return this.appointmentEndTime; }
            public AppointmentTimeItem appointmentEndTime(long appointmentEndTime){ this.appointmentEndTime = appointmentEndTime; return this; }
          
            /**
            *医生id
            **/
            public int doctorId ;
            public int getDoctorId(){ return this.doctorId; }
            public void setDoctorId(int doctorId){ this.doctorId = doctorId; }

            public int doctorId(){ return this.doctorId; }
            public AppointmentTimeItem doctorId(int doctorId){ this.doctorId = doctorId; return this; }
          
            /**
            *是否已排班（医生已领取排班）
            **/
            public boolean allotted ;
            public boolean getAllotted(){ return this.allotted; }
            public void setAllotted(boolean allotted){ this.allotted = allotted; }

            public boolean allotted(){ return this.allotted; }
            public AppointmentTimeItem allotted(boolean allotted){ this.allotted = allotted; return this; }
          
            /**
            *

是否有权限重新调整排班

            **/
            public boolean alterable ;
            public boolean getAlterable(){ return this.alterable; }
            public void setAlterable(boolean alterable){ this.alterable = alterable; }

            public boolean alterable(){ return this.alterable; }
            public AppointmentTimeItem alterable(boolean alterable){ this.alterable = alterable; return this; }
          
            /**
            *

 挂号费用

            **/
            public double registrationAmount ;
            public double getRegistrationAmount(){ return this.registrationAmount; }
            public void setRegistrationAmount(double registrationAmount){ this.registrationAmount = registrationAmount; }

            public double registrationAmount(){ return this.registrationAmount; }
            public AppointmentTimeItem registrationAmount(double registrationAmount){ this.registrationAmount = registrationAmount; return this; }
          
            /**
            *

 挂号费用

            **/
            public double discountRegistrationAmount ;
            public double getDiscountRegistrationAmount(){ return this.discountRegistrationAmount; }
            public void setDiscountRegistrationAmount(double discountRegistrationAmount){ this.discountRegistrationAmount = discountRegistrationAmount; }

            public double discountRegistrationAmount(){ return this.discountRegistrationAmount; }
            public AppointmentTimeItem discountRegistrationAmount(double discountRegistrationAmount){ this.discountRegistrationAmount = discountRegistrationAmount; return this; }
          
            /**
            *

 费用折扣（几折，如8.8则为 8.8折）

            **/
            public double discount ;
            public double getDiscount(){ return this.discount; }
            public void setDiscount(double discount){ this.discount = discount; }

            public double discount(){ return this.discount; }
            public AppointmentTimeItem discount(double discount){ this.discount = discount; return this; }
          
            /**
            *

 排班类型

            **/
            public com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType ;
            public com.isuwang.dapeng.json.demo.enums.AppointmentType getAppointmentType(){ return this.appointmentType; }
            public void setAppointmentType(com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType){ this.appointmentType = appointmentType; }

            public com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType(){ return this.appointmentType; }
            public AppointmentTimeItem appointmentType(com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType){ this.appointmentType = appointmentType; return this; }
          
            /**
            *

 时间段

            **/
            public com.isuwang.dapeng.json.demo.enums.TimeInterval timeInterval ;
            public com.isuwang.dapeng.json.demo.enums.TimeInterval getTimeInterval(){ return this.timeInterval; }
            public void setTimeInterval(com.isuwang.dapeng.json.demo.enums.TimeInterval timeInterval){ this.timeInterval = timeInterval; }

            public com.isuwang.dapeng.json.demo.enums.TimeInterval timeInterval(){ return this.timeInterval; }
            public AppointmentTimeItem timeInterval(com.isuwang.dapeng.json.demo.enums.TimeInterval timeInterval){ this.timeInterval = timeInterval; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":").append(this.id).append(",");
    stringBuilder.append("\"").append("appointmentBeginTime").append("\":").append(this.appointmentBeginTime).append(",");
    stringBuilder.append("\"").append("appointmentEndTime").append("\":").append(this.appointmentEndTime).append(",");
    stringBuilder.append("\"").append("doctorId").append("\":").append(this.doctorId).append(",");
    stringBuilder.append("\"").append("allotted").append("\":").append(this.allotted).append(",");
    stringBuilder.append("\"").append("alterable").append("\":").append(this.alterable).append(",");
    stringBuilder.append("\"").append("registrationAmount").append("\":").append(this.registrationAmount).append(",");
    stringBuilder.append("\"").append("discountRegistrationAmount").append("\":").append(this.discountRegistrationAmount).append(",");
    stringBuilder.append("\"").append("discount").append("\":").append(this.discount).append(",");
    stringBuilder.append("\"").append("appointmentType").append("\":").append(this.appointmentType).append(",");
    stringBuilder.append("\"").append("timeInterval").append("\":").append(this.timeInterval).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      