package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class AppointmentItem{
        
            /**
            *

 ID

            **/
            public int id ;
            public int getId(){ return this.id; }
            public void setId(int id){ this.id = id; }

            public int id(){ return this.id; }
            public AppointmentItem id(int id){ this.id = id; return this; }
          
            /**
            *

 医生 ID

            **/
            public int doctorId ;
            public int getDoctorId(){ return this.doctorId; }
            public void setDoctorId(int doctorId){ this.doctorId = doctorId; }

            public int doctorId(){ return this.doctorId; }
            public AppointmentItem doctorId(int doctorId){ this.doctorId = doctorId; return this; }
          
            /**
            *

 医生等级

            **/
            public int level ;
            public int getLevel(){ return this.level; }
            public void setLevel(int level){ this.level = level; }

            public int level(){ return this.level; }
            public AppointmentItem level(int level){ this.level = level; return this; }
          
            /**
            *

  医生可预约开始时间

            **/
            public long appointmentBeginTime ;
            public long getAppointmentBeginTime(){ return this.appointmentBeginTime; }
            public void setAppointmentBeginTime(long appointmentBeginTime){ this.appointmentBeginTime = appointmentBeginTime; }

            public long appointmentBeginTime(){ return this.appointmentBeginTime; }
            public AppointmentItem appointmentBeginTime(long appointmentBeginTime){ this.appointmentBeginTime = appointmentBeginTime; return this; }
          
            /**
            *

  医生可预约开始时间

            **/
            public long appointmentEndTime ;
            public long getAppointmentEndTime(){ return this.appointmentEndTime; }
            public void setAppointmentEndTime(long appointmentEndTime){ this.appointmentEndTime = appointmentEndTime; }

            public long appointmentEndTime(){ return this.appointmentEndTime; }
            public AppointmentItem appointmentEndTime(long appointmentEndTime){ this.appointmentEndTime = appointmentEndTime; return this; }
          
            /**
            *

 挂号费用

            **/
            public double registrationAmount ;
            public double getRegistrationAmount(){ return this.registrationAmount; }
            public void setRegistrationAmount(double registrationAmount){ this.registrationAmount = registrationAmount; }

            public double registrationAmount(){ return this.registrationAmount; }
            public AppointmentItem registrationAmount(double registrationAmount){ this.registrationAmount = registrationAmount; return this; }
          
            /**
            *

 患者补充的症状描述

            **/
            public double discountRegistrationAmount ;
            public double getDiscountRegistrationAmount(){ return this.discountRegistrationAmount; }
            public void setDiscountRegistrationAmount(double discountRegistrationAmount){ this.discountRegistrationAmount = discountRegistrationAmount; }

            public double discountRegistrationAmount(){ return this.discountRegistrationAmount; }
            public AppointmentItem discountRegistrationAmount(double discountRegistrationAmount){ this.discountRegistrationAmount = discountRegistrationAmount; return this; }
          
            /**
            *

 费用折扣（几折，如8.8则为 8.8折）

            **/
            public double discount ;
            public double getDiscount(){ return this.discount; }
            public void setDiscount(double discount){ this.discount = discount; }

            public double discount(){ return this.discount; }
            public AppointmentItem discount(double discount){ this.discount = discount; return this; }
          
            /**
            *

 预约状态,1:可领取[医生可以排班的](available);2:可预约(workable);3:已预约(reserved);4:已过期[当天没人预约就置为过期](refund)

            **/
            public com.isuwang.dapeng.json.demo.enums.TAppointmentStatus status ;
            public com.isuwang.dapeng.json.demo.enums.TAppointmentStatus getStatus(){ return this.status; }
            public void setStatus(com.isuwang.dapeng.json.demo.enums.TAppointmentStatus status){ this.status = status; }

            public com.isuwang.dapeng.json.demo.enums.TAppointmentStatus status(){ return this.status; }
            public AppointmentItem status(com.isuwang.dapeng.json.demo.enums.TAppointmentStatus status){ this.status = status; return this; }
          
            /**
            *

 是否可以预约

            **/
            public boolean appointmentAble ;
            public boolean getAppointmentAble(){ return this.appointmentAble; }
            public void setAppointmentAble(boolean appointmentAble){ this.appointmentAble = appointmentAble; }

            public boolean appointmentAble(){ return this.appointmentAble; }
            public AppointmentItem appointmentAble(boolean appointmentAble){ this.appointmentAble = appointmentAble; return this; }
          
            /**
            *

 创建时间

            **/
            public long createdAt ;
            public long getCreatedAt(){ return this.createdAt; }
            public void setCreatedAt(long createdAt){ this.createdAt = createdAt; }

            public long createdAt(){ return this.createdAt; }
            public AppointmentItem createdAt(long createdAt){ this.createdAt = createdAt; return this; }
          
            /**
            *



            **/
            public int createdBy ;
            public int getCreatedBy(){ return this.createdBy; }
            public void setCreatedBy(int createdBy){ this.createdBy = createdBy; }

            public int createdBy(){ return this.createdBy; }
            public AppointmentItem createdBy(int createdBy){ this.createdBy = createdBy; return this; }
          
            /**
            *

 更新时间

            **/
            public long updatedAt ;
            public long getUpdatedAt(){ return this.updatedAt; }
            public void setUpdatedAt(long updatedAt){ this.updatedAt = updatedAt; }

            public long updatedAt(){ return this.updatedAt; }
            public AppointmentItem updatedAt(long updatedAt){ this.updatedAt = updatedAt; return this; }
          
            /**
            *



            **/
            public int updatedBy ;
            public int getUpdatedBy(){ return this.updatedBy; }
            public void setUpdatedBy(int updatedBy){ this.updatedBy = updatedBy; }

            public int updatedBy(){ return this.updatedBy; }
            public AppointmentItem updatedBy(int updatedBy){ this.updatedBy = updatedBy; return this; }
          
            /**
            *

 备注

            **/
            public Optional<String> remark = Optional.empty();
            public Optional<String> getRemark(){ return this.remark; }
            public void setRemark(Optional<String> remark){ this.remark = remark; }

            public Optional<String> remark(){ return this.remark; }
            public AppointmentItem remark(Optional<String> remark){ this.remark = remark; return this; }
          
            /**
            *医生信息
            **/
            public com.isuwang.dapeng.json.demo.domain.DoctorInfo doctorInfo ;
            public com.isuwang.dapeng.json.demo.domain.DoctorInfo getDoctorInfo(){ return this.doctorInfo; }
            public void setDoctorInfo(com.isuwang.dapeng.json.demo.domain.DoctorInfo doctorInfo){ this.doctorInfo = doctorInfo; }

            public com.isuwang.dapeng.json.demo.domain.DoctorInfo doctorInfo(){ return this.doctorInfo; }
            public AppointmentItem doctorInfo(com.isuwang.dapeng.json.demo.domain.DoctorInfo doctorInfo){ this.doctorInfo = doctorInfo; return this; }
          
            /**
            *

(已预约)患者信息

            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.PatientInfo> patientInfo = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.PatientInfo> getPatientInfo(){ return this.patientInfo; }
            public void setPatientInfo(Optional<com.isuwang.dapeng.json.demo.domain.PatientInfo> patientInfo){ this.patientInfo = patientInfo; }

            public Optional<com.isuwang.dapeng.json.demo.domain.PatientInfo> patientInfo(){ return this.patientInfo; }
            public AppointmentItem patientInfo(Optional<com.isuwang.dapeng.json.demo.domain.PatientInfo> patientInfo){ this.patientInfo = patientInfo; return this; }
          
            /**
            *

(已预约)订单id

            **/
            public Optional<Integer> orderId = Optional.empty();
            public Optional<Integer> getOrderId(){ return this.orderId; }
            public void setOrderId(Optional<Integer> orderId){ this.orderId = orderId; }

            public Optional<Integer> orderId(){ return this.orderId; }
            public AppointmentItem orderId(Optional<Integer> orderId){ this.orderId = orderId; return this; }
          
            /**
            *

 排班类型

            **/
            public com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType ;
            public com.isuwang.dapeng.json.demo.enums.AppointmentType getAppointmentType(){ return this.appointmentType; }
            public void setAppointmentType(com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType){ this.appointmentType = appointmentType; }

            public com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType(){ return this.appointmentType; }
            public AppointmentItem appointmentType(com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType){ this.appointmentType = appointmentType; return this; }
          
            /**
            *

 排班类型

            **/
            public com.isuwang.dapeng.json.demo.enums.TimeInterval timeInterval ;
            public com.isuwang.dapeng.json.demo.enums.TimeInterval getTimeInterval(){ return this.timeInterval; }
            public void setTimeInterval(com.isuwang.dapeng.json.demo.enums.TimeInterval timeInterval){ this.timeInterval = timeInterval; }

            public com.isuwang.dapeng.json.demo.enums.TimeInterval timeInterval(){ return this.timeInterval; }
            public AppointmentItem timeInterval(com.isuwang.dapeng.json.demo.enums.TimeInterval timeInterval){ this.timeInterval = timeInterval; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":").append(this.id).append(",");
    stringBuilder.append("\"").append("doctorId").append("\":").append(this.doctorId).append(",");
    stringBuilder.append("\"").append("level").append("\":").append(this.level).append(",");
    stringBuilder.append("\"").append("appointmentBeginTime").append("\":").append(this.appointmentBeginTime).append(",");
    stringBuilder.append("\"").append("appointmentEndTime").append("\":").append(this.appointmentEndTime).append(",");
    stringBuilder.append("\"").append("registrationAmount").append("\":").append(this.registrationAmount).append(",");
    stringBuilder.append("\"").append("discountRegistrationAmount").append("\":").append(this.discountRegistrationAmount).append(",");
    stringBuilder.append("\"").append("discount").append("\":").append(this.discount).append(",");
    stringBuilder.append("\"").append("status").append("\":").append(this.status).append(",");
    stringBuilder.append("\"").append("appointmentAble").append("\":").append(this.appointmentAble).append(",");
    stringBuilder.append("\"").append("createdAt").append("\":").append(this.createdAt).append(",");
    stringBuilder.append("\"").append("createdBy").append("\":").append(this.createdBy).append(",");
    stringBuilder.append("\"").append("updatedAt").append("\":").append(this.updatedAt).append(",");
    stringBuilder.append("\"").append("updatedBy").append("\":").append(this.updatedBy).append(",");
    stringBuilder.append("\"").append("remark").append("\":\"").append(this.remark.isPresent()?this.remark.get():null).append("\",");
    stringBuilder.append("\"").append("doctorInfo").append("\":").append(this.doctorInfo.toString()).append(",");
    stringBuilder.append("\"").append("patientInfo").append("\":").append(this.patientInfo.isPresent()?this.patientInfo.get().toString():null).append(",");
    stringBuilder.append("\"").append("orderId").append("\":").append(this.orderId.isPresent()?this.orderId.get():null).append(",");
    stringBuilder.append("\"").append("appointmentType").append("\":").append(this.appointmentType).append(",");
    stringBuilder.append("\"").append("timeInterval").append("\":").append(this.timeInterval).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      