package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class AppointmentDoctorsByDateRequest{
        
            /**
            *
            **/
            public String date ;
            public String getDate(){ return this.date; }
            public void setDate(String date){ this.date = date; }

            public String date(){ return this.date; }
            public AppointmentDoctorsByDateRequest date(String date){ this.date = date; return this; }
          
            /**
            *
            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> getPageRequest(){ return this.pageRequest; }
            public void setPageRequest(Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest){ this.pageRequest = pageRequest; }

            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest(){ return this.pageRequest; }
            public AppointmentDoctorsByDateRequest pageRequest(Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest){ this.pageRequest = pageRequest; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("date").append("\":\"").append(this.date).append("\",");
    stringBuilder.append("\"").append("pageRequest").append("\":").append(this.pageRequest.isPresent()?this.pageRequest.get().toString():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      