package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *创建排班请求
        **/
        public class BatchAppointmentRequest{
        
            /**
            *排班医生
            **/
            public int doctorId ;
            public int getDoctorId(){ return this.doctorId; }
            public void setDoctorId(int doctorId){ this.doctorId = doctorId; }

            public int doctorId(){ return this.doctorId; }
            public BatchAppointmentRequest doctorId(int doctorId){ this.doctorId = doctorId; return this; }
          
            /**
            *排班选择情况 map<appointmentTimeId,是否选中>
            **/
            public java.util.Map<Integer, Boolean> appointmentList = new java.util.HashMap<>();
            public java.util.Map<Integer, Boolean> getAppointmentList(){ return this.appointmentList; }
            public void setAppointmentList(java.util.Map<Integer, Boolean> appointmentList){ this.appointmentList = appointmentList; }

            public java.util.Map<Integer, Boolean> appointmentList(){ return this.appointmentList; }
            public BatchAppointmentRequest appointmentList(java.util.Map<Integer, Boolean> appointmentList){ this.appointmentList = appointmentList; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("doctorId").append("\":").append(this.doctorId).append(",");
    stringBuilder.append("\"").append("appointmentList").append("\":").append(this.appointmentList).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      