package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class CountBuyTextPackPatientsResponse{
        
            /**
            *
            **/
            public int textPackPatient ;
            public int getTextPackPatient(){ return this.textPackPatient; }
            public void setTextPackPatient(int textPackPatient){ this.textPackPatient = textPackPatient; }

            public int textPackPatient(){ return this.textPackPatient; }
            public CountBuyTextPackPatientsResponse textPackPatient(int textPackPatient){ this.textPackPatient = textPackPatient; return this; }
          
            /**
            *
            **/
            public int newAddTextPackPatient ;
            public int getNewAddTextPackPatient(){ return this.newAddTextPackPatient; }
            public void setNewAddTextPackPatient(int newAddTextPackPatient){ this.newAddTextPackPatient = newAddTextPackPatient; }

            public int newAddTextPackPatient(){ return this.newAddTextPackPatient; }
            public CountBuyTextPackPatientsResponse newAddTextPackPatient(int newAddTextPackPatient){ this.newAddTextPackPatient = newAddTextPackPatient; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("textPackPatient").append("\":").append(this.textPackPatient).append(",");
    stringBuilder.append("\"").append("newAddTextPackPatient").append("\":").append(this.newAddTextPackPatient).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      