package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 心理保健套餐（优惠券）订单的下单参数 
        **/
        public class CouponOrderParams{
        
            /**
            *购买价格
            **/
            public double discountPrice ;
            public double getDiscountPrice(){ return this.discountPrice; }
            public void setDiscountPrice(double discountPrice){ this.discountPrice = discountPrice; }

            public double discountPrice(){ return this.discountPrice; }
            public CouponOrderParams discountPrice(double discountPrice){ this.discountPrice = discountPrice; return this; }
          
            /**
            *券的张数
            **/
            public int quantity ;
            public int getQuantity(){ return this.quantity; }
            public void setQuantity(int quantity){ this.quantity = quantity; }

            public int quantity(){ return this.quantity; }
            public CouponOrderParams quantity(int quantity){ this.quantity = quantity; return this; }
          
            /**
            *券的面值
            **/
            public double faceValue ;
            public double getFaceValue(){ return this.faceValue; }
            public void setFaceValue(double faceValue){ this.faceValue = faceValue; }

            public double faceValue(){ return this.faceValue; }
            public CouponOrderParams faceValue(double faceValue){ this.faceValue = faceValue; return this; }
          
            /**
            *

 失效时间

            **/
            public long expiredAt ;
            public long getExpiredAt(){ return this.expiredAt; }
            public void setExpiredAt(long expiredAt){ this.expiredAt = expiredAt; }

            public long expiredAt(){ return this.expiredAt; }
            public CouponOrderParams expiredAt(long expiredAt){ this.expiredAt = expiredAt; return this; }
          
            /**
            *（已购买）剩余数量
            **/
            public int remain ;
            public int getRemain(){ return this.remain; }
            public void setRemain(int remain){ this.remain = remain; }

            public int remain(){ return this.remain; }
            public CouponOrderParams remain(int remain){ this.remain = remain; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("discountPrice").append("\":").append(this.discountPrice).append(",");
    stringBuilder.append("\"").append("quantity").append("\":").append(this.quantity).append(",");
    stringBuilder.append("\"").append("faceValue").append("\":").append(this.faceValue).append(",");
    stringBuilder.append("\"").append("expiredAt").append("\":").append(this.expiredAt).append(",");
    stringBuilder.append("\"").append("remain").append("\":").append(this.remain).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      