package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class CreateOrderForOffLineRequest{
        
            /**
            *

 医生 ID

            **/
            public int doctorId ;
            public int getDoctorId(){ return this.doctorId; }
            public void setDoctorId(int doctorId){ this.doctorId = doctorId; }

            public int doctorId(){ return this.doctorId; }
            public CreateOrderForOffLineRequest doctorId(int doctorId){ this.doctorId = doctorId; return this; }
          
            /**
            *

 线下患者 ID, 新增患者，ID为0

            **/
            public int offlinePatientId ;
            public int getOfflinePatientId(){ return this.offlinePatientId; }
            public void setOfflinePatientId(int offlinePatientId){ this.offlinePatientId = offlinePatientId; }

            public int offlinePatientId(){ return this.offlinePatientId; }
            public CreateOrderForOffLineRequest offlinePatientId(int offlinePatientId){ this.offlinePatientId = offlinePatientId; return this; }
          
            /**
            *

 线下患者 手机号码

            **/
            public String offlinePatientPhone ;
            public String getOfflinePatientPhone(){ return this.offlinePatientPhone; }
            public void setOfflinePatientPhone(String offlinePatientPhone){ this.offlinePatientPhone = offlinePatientPhone; }

            public String offlinePatientPhone(){ return this.offlinePatientPhone; }
            public CreateOrderForOffLineRequest offlinePatientPhone(String offlinePatientPhone){ this.offlinePatientPhone = offlinePatientPhone; return this; }
          
            /**
            *

 线下患者 姓名

            **/
            public String offlinePatientName ;
            public String getOfflinePatientName(){ return this.offlinePatientName; }
            public void setOfflinePatientName(String offlinePatientName){ this.offlinePatientName = offlinePatientName; }

            public String offlinePatientName(){ return this.offlinePatientName; }
            public CreateOrderForOffLineRequest offlinePatientName(String offlinePatientName){ this.offlinePatientName = offlinePatientName; return this; }
          
            /**
            *

 线下患者 性别

            **/
            public com.isuwang.dapeng.json.demo.enums.Gender offlinePatientGender ;
            public com.isuwang.dapeng.json.demo.enums.Gender getOfflinePatientGender(){ return this.offlinePatientGender; }
            public void setOfflinePatientGender(com.isuwang.dapeng.json.demo.enums.Gender offlinePatientGender){ this.offlinePatientGender = offlinePatientGender; }

            public com.isuwang.dapeng.json.demo.enums.Gender offlinePatientGender(){ return this.offlinePatientGender; }
            public CreateOrderForOffLineRequest offlinePatientGender(com.isuwang.dapeng.json.demo.enums.Gender offlinePatientGender){ this.offlinePatientGender = offlinePatientGender; return this; }
          
            /**
            *

 线下患者 年龄

            **/
            public int offlinePatientAge ;
            public int getOfflinePatientAge(){ return this.offlinePatientAge; }
            public void setOfflinePatientAge(int offlinePatientAge){ this.offlinePatientAge = offlinePatientAge; }

            public int offlinePatientAge(){ return this.offlinePatientAge; }
            public CreateOrderForOffLineRequest offlinePatientAge(int offlinePatientAge){ this.offlinePatientAge = offlinePatientAge; return this; }
          
            /**
            *

 患者补充的症状描述

            **/
            public String patientInformationContent ;
            public String getPatientInformationContent(){ return this.patientInformationContent; }
            public void setPatientInformationContent(String patientInformationContent){ this.patientInformationContent = patientInformationContent; }

            public String patientInformationContent(){ return this.patientInformationContent; }
            public CreateOrderForOffLineRequest patientInformationContent(String patientInformationContent){ this.patientInformationContent = patientInformationContent; return this; }
          
            /**
            *

 预约信息 ID

            **/
            public int appointmentId ;
            public int getAppointmentId(){ return this.appointmentId; }
            public void setAppointmentId(int appointmentId){ this.appointmentId = appointmentId; }

            public int appointmentId(){ return this.appointmentId; }
            public CreateOrderForOffLineRequest appointmentId(int appointmentId){ this.appointmentId = appointmentId; return this; }
          
            /**
            *

 备注

            **/
            public Optional<String> remark = Optional.empty();
            public Optional<String> getRemark(){ return this.remark; }
            public void setRemark(Optional<String> remark){ this.remark = remark; }

            public Optional<String> remark(){ return this.remark; }
            public CreateOrderForOffLineRequest remark(Optional<String> remark){ this.remark = remark; return this; }
          
            /**
            *

 订单状态,仅限 待支付和待诊断[已付款]

            **/
            public Optional<com.isuwang.dapeng.json.demo.enums.TOrderStatus> status = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.enums.TOrderStatus> getStatus(){ return this.status; }
            public void setStatus(Optional<com.isuwang.dapeng.json.demo.enums.TOrderStatus> status){ this.status = status; }

            public Optional<com.isuwang.dapeng.json.demo.enums.TOrderStatus> status(){ return this.status; }
            public CreateOrderForOffLineRequest status(Optional<com.isuwang.dapeng.json.demo.enums.TOrderStatus> status){ this.status = status; return this; }
          
            /**
            *

 治疗方式

            **/
            public com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode therapyMode ;
            public com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode getTherapyMode(){ return this.therapyMode; }
            public void setTherapyMode(com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode therapyMode){ this.therapyMode = therapyMode; }

            public com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode therapyMode(){ return this.therapyMode; }
            public CreateOrderForOffLineRequest therapyMode(com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode therapyMode){ this.therapyMode = therapyMode; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("doctorId").append("\":").append(this.doctorId).append(",");
    stringBuilder.append("\"").append("offlinePatientId").append("\":").append(this.offlinePatientId).append(",");
    stringBuilder.append("\"").append("offlinePatientPhone").append("\":\"").append(this.offlinePatientPhone).append("\",");
    stringBuilder.append("\"").append("offlinePatientName").append("\":\"").append(this.offlinePatientName).append("\",");
    stringBuilder.append("\"").append("offlinePatientGender").append("\":").append(this.offlinePatientGender).append(",");
    stringBuilder.append("\"").append("offlinePatientAge").append("\":").append(this.offlinePatientAge).append(",");
    stringBuilder.append("\"").append("patientInformationContent").append("\":\"").append(this.patientInformationContent).append("\",");
    stringBuilder.append("\"").append("appointmentId").append("\":").append(this.appointmentId).append(",");
    stringBuilder.append("\"").append("remark").append("\":\"").append(this.remark.isPresent()?this.remark.get():null).append("\",");
    stringBuilder.append("\"").append("status").append("\":").append(this.status.isPresent()?this.status.get():null).append(",");
    stringBuilder.append("\"").append("therapyMode").append("\":").append(this.therapyMode).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      