package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class CreateOfflinePatientRequest{
        
            /**
            *

 姓名

            **/
            public String name ;
            public String getName(){ return this.name; }
            public void setName(String name){ this.name = name; }

            public String name(){ return this.name; }
            public CreateOfflinePatientRequest name(String name){ this.name = name; return this; }
          
            /**
            *

 手机号码

            **/
            public String phone ;
            public String getPhone(){ return this.phone; }
            public void setPhone(String phone){ this.phone = phone; }

            public String phone(){ return this.phone; }
            public CreateOfflinePatientRequest phone(String phone){ this.phone = phone; return this; }
          
            /**
            *

 性别

            **/
            public com.isuwang.dapeng.json.demo.enums.Gender gender ;
            public com.isuwang.dapeng.json.demo.enums.Gender getGender(){ return this.gender; }
            public void setGender(com.isuwang.dapeng.json.demo.enums.Gender gender){ this.gender = gender; }

            public com.isuwang.dapeng.json.demo.enums.Gender gender(){ return this.gender; }
            public CreateOfflinePatientRequest gender(com.isuwang.dapeng.json.demo.enums.Gender gender){ this.gender = gender; return this; }
          
            /**
            *

 年龄

            **/
            public int age ;
            public int getAge(){ return this.age; }
            public void setAge(int age){ this.age = age; }

            public int age(){ return this.age; }
            public CreateOfflinePatientRequest age(int age){ this.age = age; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("name").append("\":\"").append(this.name).append("\",");
    stringBuilder.append("\"").append("phone").append("\":\"").append(this.phone).append("\",");
    stringBuilder.append("\"").append("gender").append("\":").append(this.gender).append(",");
    stringBuilder.append("\"").append("age").append("\":").append(this.age).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      