package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class DiagnoseItem{
        
            /**
            *

 id

            **/
            public int id ;
            public int getId(){ return this.id; }
            public void setId(int id){ this.id = id; }

            public int id(){ return this.id; }
            public DiagnoseItem id(int id){ this.id = id; return this; }
          
            /**
            *

 doctorId

            **/
            public int doctorId ;
            public int getDoctorId(){ return this.doctorId; }
            public void setDoctorId(int doctorId){ this.doctorId = doctorId; }

            public int doctorId(){ return this.doctorId; }
            public DiagnoseItem doctorId(int doctorId){ this.doctorId = doctorId; return this; }
          
            /**
            *

 医生姓名

            **/
            public String doctorName ;
            public String getDoctorName(){ return this.doctorName; }
            public void setDoctorName(String doctorName){ this.doctorName = doctorName; }

            public String doctorName(){ return this.doctorName; }
            public DiagnoseItem doctorName(String doctorName){ this.doctorName = doctorName; return this; }
          
            /**
            *

 医生头像

            **/
            public String doctorHeadImage ;
            public String getDoctorHeadImage(){ return this.doctorHeadImage; }
            public void setDoctorHeadImage(String doctorHeadImage){ this.doctorHeadImage = doctorHeadImage; }

            public String doctorHeadImage(){ return this.doctorHeadImage; }
            public DiagnoseItem doctorHeadImage(String doctorHeadImage){ this.doctorHeadImage = doctorHeadImage; return this; }
          
            /**
            *

  patientId

            **/
            public int patientId ;
            public int getPatientId(){ return this.patientId; }
            public void setPatientId(int patientId){ this.patientId = patientId; }

            public int patientId(){ return this.patientId; }
            public DiagnoseItem patientId(int patientId){ this.patientId = patientId; return this; }
          
            /**
            *

  病人姓名

            **/
            public String patientName ;
            public String getPatientName(){ return this.patientName; }
            public void setPatientName(String patientName){ this.patientName = patientName; }

            public String patientName(){ return this.patientName; }
            public DiagnoseItem patientName(String patientName){ this.patientName = patientName; return this; }
          
            /**
            *

  患者头像

            **/
            public String patientHeadImage ;
            public String getPatientHeadImage(){ return this.patientHeadImage; }
            public void setPatientHeadImage(String patientHeadImage){ this.patientHeadImage = patientHeadImage; }

            public String patientHeadImage(){ return this.patientHeadImage; }
            public DiagnoseItem patientHeadImage(String patientHeadImage){ this.patientHeadImage = patientHeadImage; return this; }
          
            /**
            *

  诊断内容

            **/
            public String content ;
            public String getContent(){ return this.content; }
            public void setContent(String content){ this.content = content; }

            public String content(){ return this.content; }
            public DiagnoseItem content(String content){ this.content = content; return this; }
          
            /**
            *

 时间

            **/
            public long createdAt ;
            public long getCreatedAt(){ return this.createdAt; }
            public void setCreatedAt(long createdAt){ this.createdAt = createdAt; }

            public long createdAt(){ return this.createdAt; }
            public DiagnoseItem createdAt(long createdAt){ this.createdAt = createdAt; return this; }
          
            /**
            *
            **/
            public boolean read ;
            public boolean getRead(){ return this.read; }
            public void setRead(boolean read){ this.read = read; }

            public boolean read(){ return this.read; }
            public DiagnoseItem read(boolean read){ this.read = read; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":").append(this.id).append(",");
    stringBuilder.append("\"").append("doctorId").append("\":").append(this.doctorId).append(",");
    stringBuilder.append("\"").append("doctorName").append("\":\"").append(this.doctorName).append("\",");
    stringBuilder.append("\"").append("doctorHeadImage").append("\":\"").append(this.doctorHeadImage).append("\",");
    stringBuilder.append("\"").append("patientId").append("\":").append(this.patientId).append(",");
    stringBuilder.append("\"").append("patientName").append("\":\"").append(this.patientName).append("\",");
    stringBuilder.append("\"").append("patientHeadImage").append("\":\"").append(this.patientHeadImage).append("\",");
    stringBuilder.append("\"").append("content").append("\":\"").append(this.content).append("\",");
    stringBuilder.append("\"").append("createdAt").append("\":").append(this.createdAt).append(",");
    stringBuilder.append("\"").append("read").append("\":").append(this.read).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      