package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class ListPriceRuleResponse{
        
            /**
            *推荐分页响应包
            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> getPageResponse(){ return this.pageResponse; }
            public void setPageResponse(Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse){ this.pageResponse = pageResponse; }

            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse(){ return this.pageResponse; }
            public ListPriceRuleResponse pageResponse(Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse){ this.pageResponse = pageResponse; return this; }
          
            /**
            *
            **/
            public java.util.List<com.isuwang.dapeng.json.demo.domain.PriceRuleItem> priceRuleList = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.domain.PriceRuleItem> getPriceRuleList(){ return this.priceRuleList; }
            public void setPriceRuleList(java.util.List<com.isuwang.dapeng.json.demo.domain.PriceRuleItem> priceRuleList){ this.priceRuleList = priceRuleList; }

            public java.util.List<com.isuwang.dapeng.json.demo.domain.PriceRuleItem> priceRuleList(){ return this.priceRuleList; }
            public ListPriceRuleResponse priceRuleList(java.util.List<com.isuwang.dapeng.json.demo.domain.PriceRuleItem> priceRuleList){ this.priceRuleList = priceRuleList; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageResponse").append("\":").append(this.pageResponse.isPresent()?this.pageResponse.get().toString():null).append(",");
    stringBuilder.append("\"").append("priceRuleList").append("\":").append(this.priceRuleList).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      