package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class ListTreatPlansResponse{
        
            /**
            *
            **/
            public java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> todyPlans = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> getTodyPlans(){ return this.todyPlans; }
            public void setTodyPlans(java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> todyPlans){ this.todyPlans = todyPlans; }

            public java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> todyPlans(){ return this.todyPlans; }
            public ListTreatPlansResponse todyPlans(java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> todyPlans){ this.todyPlans = todyPlans; return this; }
          
            /**
            *
            **/
            public java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> futurePlans = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> getFuturePlans(){ return this.futurePlans; }
            public void setFuturePlans(java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> futurePlans){ this.futurePlans = futurePlans; }

            public java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> futurePlans(){ return this.futurePlans; }
            public ListTreatPlansResponse futurePlans(java.util.List<com.isuwang.dapeng.json.demo.domain.TreatPlanItem> futurePlans){ this.futurePlans = futurePlans; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("todyPlans").append("\":").append(this.todyPlans).append(",");
    stringBuilder.append("\"").append("futurePlans").append("\":").append(this.futurePlans).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      