package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *查询排班医生请求
        **/
        public class ListAppointmentDoctorsRequest{
        
            /**
            *
            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> getPageRequest(){ return this.pageRequest; }
            public void setPageRequest(Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest){ this.pageRequest = pageRequest; }

            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest(){ return this.pageRequest; }
            public ListAppointmentDoctorsRequest pageRequest(Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest){ this.pageRequest = pageRequest; return this; }
          
            /**
            *医生标签，空表示匹配全部医生,必须登录用户才能使用该查询条件
            **/
            public java.util.List<String> labels = new java.util.ArrayList();
            public java.util.List<String> getLabels(){ return this.labels; }
            public void setLabels(java.util.List<String> labels){ this.labels = labels; }

            public java.util.List<String> labels(){ return this.labels; }
            public ListAppointmentDoctorsRequest labels(java.util.List<String> labels){ this.labels = labels; return this; }
          
            /**
            *

 排班类型

            **/
            public Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> appointmentType = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> getAppointmentType(){ return this.appointmentType; }
            public void setAppointmentType(Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> appointmentType){ this.appointmentType = appointmentType; }

            public Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> appointmentType(){ return this.appointmentType; }
            public ListAppointmentDoctorsRequest appointmentType(Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> appointmentType){ this.appointmentType = appointmentType; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageRequest").append("\":").append(this.pageRequest.isPresent()?this.pageRequest.get().toString():null).append(",");
    stringBuilder.append("\"").append("labels").append("\":").append(this.labels).append(",");
    stringBuilder.append("\"").append("appointmentType").append("\":").append(this.appointmentType.isPresent()?this.appointmentType.get():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      