package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *今日值班医生
        **/
        public class ListDoctorOnDutyResponse{
        
            /**
            *

 分页

            **/
            public com.isuwang.dapeng.json.demo.domain.PageResponse pageResponse ;
            public com.isuwang.dapeng.json.demo.domain.PageResponse getPageResponse(){ return this.pageResponse; }
            public void setPageResponse(com.isuwang.dapeng.json.demo.domain.PageResponse pageResponse){ this.pageResponse = pageResponse; }

            public com.isuwang.dapeng.json.demo.domain.PageResponse pageResponse(){ return this.pageResponse; }
            public ListDoctorOnDutyResponse pageResponse(com.isuwang.dapeng.json.demo.domain.PageResponse pageResponse){ this.pageResponse = pageResponse; return this; }
          
            /**
            *
            **/
            public java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentDoctorByDate> doctors = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentDoctorByDate> getDoctors(){ return this.doctors; }
            public void setDoctors(java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentDoctorByDate> doctors){ this.doctors = doctors; }

            public java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentDoctorByDate> doctors(){ return this.doctors; }
            public ListDoctorOnDutyResponse doctors(java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentDoctorByDate> doctors){ this.doctors = doctors; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageResponse").append("\":").append(this.pageResponse.toString()).append(",");
    stringBuilder.append("\"").append("doctors").append("\":").append(this.doctors).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      