package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class ListOrderRequest{
        
            /**
            *
            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> getPageRequest(){ return this.pageRequest; }
            public void setPageRequest(Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest){ this.pageRequest = pageRequest; }

            public Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest(){ return this.pageRequest; }
            public ListOrderRequest pageRequest(Optional<com.isuwang.dapeng.json.demo.domain.PageRequest> pageRequest){ this.pageRequest = pageRequest; return this; }
          
            /**
            *匹配状态（多选），如果空，则表示全部状态
            **/
            public java.util.List<com.isuwang.dapeng.json.demo.enums.TOrderStatus> statuses = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.enums.TOrderStatus> getStatuses(){ return this.statuses; }
            public void setStatuses(java.util.List<com.isuwang.dapeng.json.demo.enums.TOrderStatus> statuses){ this.statuses = statuses; }

            public java.util.List<com.isuwang.dapeng.json.demo.enums.TOrderStatus> statuses(){ return this.statuses; }
            public ListOrderRequest statuses(java.util.List<com.isuwang.dapeng.json.demo.enums.TOrderStatus> statuses){ this.statuses = statuses; return this; }
          
            /**
            *患者ID
            **/
            public Optional<Integer> patientId = Optional.empty();
            public Optional<Integer> getPatientId(){ return this.patientId; }
            public void setPatientId(Optional<Integer> patientId){ this.patientId = patientId; }

            public Optional<Integer> patientId(){ return this.patientId; }
            public ListOrderRequest patientId(Optional<Integer> patientId){ this.patientId = patientId; return this; }
          
            /**
            *医生ID
            **/
            public Optional<Integer> doctorId = Optional.empty();
            public Optional<Integer> getDoctorId(){ return this.doctorId; }
            public void setDoctorId(Optional<Integer> doctorId){ this.doctorId = doctorId; }

            public Optional<Integer> doctorId(){ return this.doctorId; }
            public ListOrderRequest doctorId(Optional<Integer> doctorId){ this.doctorId = doctorId; return this; }
          
            /**
            *医生ID集合
            **/
            public java.util.List<Integer> doctorIdList = new java.util.ArrayList();
            public java.util.List<Integer> getDoctorIdList(){ return this.doctorIdList; }
            public void setDoctorIdList(java.util.List<Integer> doctorIdList){ this.doctorIdList = doctorIdList; }

            public java.util.List<Integer> doctorIdList(){ return this.doctorIdList; }
            public ListOrderRequest doctorIdList(java.util.List<Integer> doctorIdList){ this.doctorIdList = doctorIdList; return this; }
          
            /**
            *开始时间
            **/
            public Optional<Long> beginTime = Optional.empty();
            public Optional<Long> getBeginTime(){ return this.beginTime; }
            public void setBeginTime(Optional<Long> beginTime){ this.beginTime = beginTime; }

            public Optional<Long> beginTime(){ return this.beginTime; }
            public ListOrderRequest beginTime(Optional<Long> beginTime){ this.beginTime = beginTime; return this; }
          
            /**
            *结束时间
            **/
            public Optional<Long> endTime = Optional.empty();
            public Optional<Long> getEndTime(){ return this.endTime; }
            public void setEndTime(Optional<Long> endTime){ this.endTime = endTime; }

            public Optional<Long> endTime(){ return this.endTime; }
            public ListOrderRequest endTime(Optional<Long> endTime){ this.endTime = endTime; return this; }
          
            /**
            *是否已经创建诊疗报告
            **/
            public Optional<Boolean> exitDiagnose = Optional.empty();
            public Optional<Boolean> getExitDiagnose(){ return this.exitDiagnose; }
            public void setExitDiagnose(Optional<Boolean> exitDiagnose){ this.exitDiagnose = exitDiagnose; }

            public Optional<Boolean> exitDiagnose(){ return this.exitDiagnose; }
            public ListOrderRequest exitDiagnose(Optional<Boolean> exitDiagnose){ this.exitDiagnose = exitDiagnose; return this; }
          
            /**
            *支付方式
            **/
            public Optional<com.isuwang.dapeng.json.demo.enums.TOrderPayType> payType = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.enums.TOrderPayType> getPayType(){ return this.payType; }
            public void setPayType(Optional<com.isuwang.dapeng.json.demo.enums.TOrderPayType> payType){ this.payType = payType; }

            public Optional<com.isuwang.dapeng.json.demo.enums.TOrderPayType> payType(){ return this.payType; }
            public ListOrderRequest payType(Optional<com.isuwang.dapeng.json.demo.enums.TOrderPayType> payType){ this.payType = payType; return this; }
          
            /**
            *预约方式
            **/
            public Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> appointmentType = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> getAppointmentType(){ return this.appointmentType; }
            public void setAppointmentType(Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> appointmentType){ this.appointmentType = appointmentType; }

            public Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> appointmentType(){ return this.appointmentType; }
            public ListOrderRequest appointmentType(Optional<com.isuwang.dapeng.json.demo.enums.AppointmentType> appointmentType){ this.appointmentType = appointmentType; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageRequest").append("\":").append(this.pageRequest.isPresent()?this.pageRequest.get().toString():null).append(",");
    stringBuilder.append("\"").append("statuses").append("\":").append(this.statuses).append(",");
    stringBuilder.append("\"").append("patientId").append("\":").append(this.patientId.isPresent()?this.patientId.get():null).append(",");
    stringBuilder.append("\"").append("doctorId").append("\":").append(this.doctorId.isPresent()?this.doctorId.get():null).append(",");
    stringBuilder.append("\"").append("doctorIdList").append("\":").append(this.doctorIdList).append(",");
    stringBuilder.append("\"").append("beginTime").append("\":").append(this.beginTime.isPresent()?this.beginTime.get():null).append(",");
    stringBuilder.append("\"").append("endTime").append("\":").append(this.endTime.isPresent()?this.endTime.get():null).append(",");
    stringBuilder.append("\"").append("exitDiagnose").append("\":").append(this.exitDiagnose.isPresent()?this.exitDiagnose.get():null).append(",");
    stringBuilder.append("\"").append("payType").append("\":").append(this.payType.isPresent()?this.payType.get():null).append(",");
    stringBuilder.append("\"").append("appointmentType").append("\":").append(this.appointmentType.isPresent()?this.appointmentType.get():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      