package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class ListAppointmentPatientResponse{
        
            /**
            *

 分页

            **/
            public com.isuwang.dapeng.json.demo.domain.PageResponse pageResponse ;
            public com.isuwang.dapeng.json.demo.domain.PageResponse getPageResponse(){ return this.pageResponse; }
            public void setPageResponse(com.isuwang.dapeng.json.demo.domain.PageResponse pageResponse){ this.pageResponse = pageResponse; }

            public com.isuwang.dapeng.json.demo.domain.PageResponse pageResponse(){ return this.pageResponse; }
            public ListAppointmentPatientResponse pageResponse(com.isuwang.dapeng.json.demo.domain.PageResponse pageResponse){ this.pageResponse = pageResponse; return this; }
          
            /**
            *

 患者列表

            **/
            public java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentPatient> patients = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentPatient> getPatients(){ return this.patients; }
            public void setPatients(java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentPatient> patients){ this.patients = patients; }

            public java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentPatient> patients(){ return this.patients; }
            public ListAppointmentPatientResponse patients(java.util.List<com.isuwang.dapeng.json.demo.domain.AppointmentPatient> patients){ this.patients = patients; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageResponse").append("\":").append(this.pageResponse.toString()).append(",");
    stringBuilder.append("\"").append("patients").append("\":").append(this.patients).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      