package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *推荐信息
        **/
        public class ListRecommendsRespone{
        
            /**
            *推荐分页响应包
            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> getPageResponse(){ return this.pageResponse; }
            public void setPageResponse(Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse){ this.pageResponse = pageResponse; }

            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse(){ return this.pageResponse; }
            public ListRecommendsRespone pageResponse(Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse){ this.pageResponse = pageResponse; return this; }
          
            /**
            *
            **/
            public java.util.List<com.isuwang.dapeng.json.demo.domain.RecommendItem> recommendList = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.domain.RecommendItem> getRecommendList(){ return this.recommendList; }
            public void setRecommendList(java.util.List<com.isuwang.dapeng.json.demo.domain.RecommendItem> recommendList){ this.recommendList = recommendList; }

            public java.util.List<com.isuwang.dapeng.json.demo.domain.RecommendItem> recommendList(){ return this.recommendList; }
            public ListRecommendsRespone recommendList(java.util.List<com.isuwang.dapeng.json.demo.domain.RecommendItem> recommendList){ this.recommendList = recommendList; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("pageResponse").append("\":").append(this.pageResponse.isPresent()?this.pageResponse.get().toString():null).append(",");
    stringBuilder.append("\"").append("recommendList").append("\":").append(this.recommendList).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      