package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 订单列表响应

        **/
        public class ListTextPackOrderForDoctorResponse{
        
            /**
            *

  订单列表

            **/
            public java.util.List<com.isuwang.dapeng.json.demo.domain.OrderItem> orderItems = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.domain.OrderItem> getOrderItems(){ return this.orderItems; }
            public void setOrderItems(java.util.List<com.isuwang.dapeng.json.demo.domain.OrderItem> orderItems){ this.orderItems = orderItems; }

            public java.util.List<com.isuwang.dapeng.json.demo.domain.OrderItem> orderItems(){ return this.orderItems; }
            public ListTextPackOrderForDoctorResponse orderItems(java.util.List<com.isuwang.dapeng.json.demo.domain.OrderItem> orderItems){ this.orderItems = orderItems; return this; }
          
            /**
            *

  分页查询响应

            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> getPageResponse(){ return this.pageResponse; }
            public void setPageResponse(Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse){ this.pageResponse = pageResponse; }

            public Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse(){ return this.pageResponse; }
            public ListTextPackOrderForDoctorResponse pageResponse(Optional<com.isuwang.dapeng.json.demo.domain.PageResponse> pageResponse){ this.pageResponse = pageResponse; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("orderItems").append("\":").append(this.orderItems).append(",");
    stringBuilder.append("\"").append("pageResponse").append("\":").append(this.pageResponse.isPresent()?this.pageResponse.get().toString():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      