package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

   修改订单状态请求

        **/
        public class ModifyOrderStatusRequest{
        
            /**
            *
            **/
            public int orderId ;
            public int getOrderId(){ return this.orderId; }
            public void setOrderId(int orderId){ this.orderId = orderId; }

            public int orderId(){ return this.orderId; }
            public ModifyOrderStatusRequest orderId(int orderId){ this.orderId = orderId; return this; }
          
            /**
            *
            **/
            public com.isuwang.dapeng.json.demo.enums.TOrderStatus orderStatus ;
            public com.isuwang.dapeng.json.demo.enums.TOrderStatus getOrderStatus(){ return this.orderStatus; }
            public void setOrderStatus(com.isuwang.dapeng.json.demo.enums.TOrderStatus orderStatus){ this.orderStatus = orderStatus; }

            public com.isuwang.dapeng.json.demo.enums.TOrderStatus orderStatus(){ return this.orderStatus; }
            public ModifyOrderStatusRequest orderStatus(com.isuwang.dapeng.json.demo.enums.TOrderStatus orderStatus){ this.orderStatus = orderStatus; return this; }
          
            /**
            *备注
            **/
            public Optional<String> remark = Optional.empty();
            public Optional<String> getRemark(){ return this.remark; }
            public void setRemark(Optional<String> remark){ this.remark = remark; }

            public Optional<String> remark(){ return this.remark; }
            public ModifyOrderStatusRequest remark(Optional<String> remark){ this.remark = remark; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("orderId").append("\":").append(this.orderId).append(",");
    stringBuilder.append("\"").append("orderStatus").append("\":").append(this.orderStatus).append(",");
    stringBuilder.append("\"").append("remark").append("\":\"").append(this.remark.isPresent()?this.remark.get():null).append("\",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      