package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class ModifyOrderForOfflineRequest{
        
            /**
            *

 订单ID

            **/
            public int orderId ;
            public int getOrderId(){ return this.orderId; }
            public void setOrderId(int orderId){ this.orderId = orderId; }

            public int orderId(){ return this.orderId; }
            public ModifyOrderForOfflineRequest orderId(int orderId){ this.orderId = orderId; return this; }
          
            /**
            *

 线下患者 姓名

            **/
            public String offlinePatientName ;
            public String getOfflinePatientName(){ return this.offlinePatientName; }
            public void setOfflinePatientName(String offlinePatientName){ this.offlinePatientName = offlinePatientName; }

            public String offlinePatientName(){ return this.offlinePatientName; }
            public ModifyOrderForOfflineRequest offlinePatientName(String offlinePatientName){ this.offlinePatientName = offlinePatientName; return this; }
          
            /**
            *

 线下患者 性别

            **/
            public com.isuwang.dapeng.json.demo.enums.Gender offlinePatientGender ;
            public com.isuwang.dapeng.json.demo.enums.Gender getOfflinePatientGender(){ return this.offlinePatientGender; }
            public void setOfflinePatientGender(com.isuwang.dapeng.json.demo.enums.Gender offlinePatientGender){ this.offlinePatientGender = offlinePatientGender; }

            public com.isuwang.dapeng.json.demo.enums.Gender offlinePatientGender(){ return this.offlinePatientGender; }
            public ModifyOrderForOfflineRequest offlinePatientGender(com.isuwang.dapeng.json.demo.enums.Gender offlinePatientGender){ this.offlinePatientGender = offlinePatientGender; return this; }
          
            /**
            *

 线下患者 年龄

            **/
            public int offlinePatientAge ;
            public int getOfflinePatientAge(){ return this.offlinePatientAge; }
            public void setOfflinePatientAge(int offlinePatientAge){ this.offlinePatientAge = offlinePatientAge; }

            public int offlinePatientAge(){ return this.offlinePatientAge; }
            public ModifyOrderForOfflineRequest offlinePatientAge(int offlinePatientAge){ this.offlinePatientAge = offlinePatientAge; return this; }
          
            /**
            *

 患者补充的症状描述

            **/
            public String patientInformationContent ;
            public String getPatientInformationContent(){ return this.patientInformationContent; }
            public void setPatientInformationContent(String patientInformationContent){ this.patientInformationContent = patientInformationContent; }

            public String patientInformationContent(){ return this.patientInformationContent; }
            public ModifyOrderForOfflineRequest patientInformationContent(String patientInformationContent){ this.patientInformationContent = patientInformationContent; return this; }
          
            /**
            *

 备注

            **/
            public Optional<String> remark = Optional.empty();
            public Optional<String> getRemark(){ return this.remark; }
            public void setRemark(Optional<String> remark){ this.remark = remark; }

            public Optional<String> remark(){ return this.remark; }
            public ModifyOrderForOfflineRequest remark(Optional<String> remark){ this.remark = remark; return this; }
          
            /**
            *

 治疗方式

            **/
            public com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode therapyMode ;
            public com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode getTherapyMode(){ return this.therapyMode; }
            public void setTherapyMode(com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode therapyMode){ this.therapyMode = therapyMode; }

            public com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode therapyMode(){ return this.therapyMode; }
            public ModifyOrderForOfflineRequest therapyMode(com.isuwang.dapeng.json.demo.enums.TOrderTherapyMode therapyMode){ this.therapyMode = therapyMode; return this; }
          
            /**
            *

 是否首诊

            **/
            public boolean firstTherapy ;
            public boolean getFirstTherapy(){ return this.firstTherapy; }
            public void setFirstTherapy(boolean firstTherapy){ this.firstTherapy = firstTherapy; }

            public boolean firstTherapy(){ return this.firstTherapy; }
            public ModifyOrderForOfflineRequest firstTherapy(boolean firstTherapy){ this.firstTherapy = firstTherapy; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("orderId").append("\":").append(this.orderId).append(",");
    stringBuilder.append("\"").append("offlinePatientName").append("\":\"").append(this.offlinePatientName).append("\",");
    stringBuilder.append("\"").append("offlinePatientGender").append("\":").append(this.offlinePatientGender).append(",");
    stringBuilder.append("\"").append("offlinePatientAge").append("\":").append(this.offlinePatientAge).append(",");
    stringBuilder.append("\"").append("patientInformationContent").append("\":\"").append(this.patientInformationContent).append("\",");
    stringBuilder.append("\"").append("remark").append("\":\"").append(this.remark.isPresent()?this.remark.get():null).append("\",");
    stringBuilder.append("\"").append("therapyMode").append("\":").append(this.therapyMode).append(",");
    stringBuilder.append("\"").append("firstTherapy").append("\":").append(this.firstTherapy).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      