package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class PatientHomePageSliderNoticeRequest{
        
            /**
            *

 返回记录数

            **/
            public Optional<Integer> limit = Optional.empty();
            public Optional<Integer> getLimit(){ return this.limit; }
            public void setLimit(Optional<Integer> limit){ this.limit = limit; }

            public Optional<Integer> limit(){ return this.limit; }
            public PatientHomePageSliderNoticeRequest limit(Optional<Integer> limit){ this.limit = limit; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("limit").append("\":").append(this.limit.isPresent()?this.limit.get():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      