package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class PatientHomePageSliderNoticeResponse{
        
            /**
            *
            **/
            public java.util.List<com.isuwang.dapeng.json.demo.domain.SliderNoticeItem> noticeItemList = new java.util.ArrayList();
            public java.util.List<com.isuwang.dapeng.json.demo.domain.SliderNoticeItem> getNoticeItemList(){ return this.noticeItemList; }
            public void setNoticeItemList(java.util.List<com.isuwang.dapeng.json.demo.domain.SliderNoticeItem> noticeItemList){ this.noticeItemList = noticeItemList; }

            public java.util.List<com.isuwang.dapeng.json.demo.domain.SliderNoticeItem> noticeItemList(){ return this.noticeItemList; }
            public PatientHomePageSliderNoticeResponse noticeItemList(java.util.List<com.isuwang.dapeng.json.demo.domain.SliderNoticeItem> noticeItemList){ this.noticeItemList = noticeItemList; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("noticeItemList").append("\":").append(this.noticeItemList).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      