package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

  订单支付成功回调请求

        **/
        public class PayNotifyRequest{
        
            /**
            *
            **/
            public String orderNum ;
            public String getOrderNum(){ return this.orderNum; }
            public void setOrderNum(String orderNum){ this.orderNum = orderNum; }

            public String orderNum(){ return this.orderNum; }
            public PayNotifyRequest orderNum(String orderNum){ this.orderNum = orderNum; return this; }
          
            /**
            *
            **/
            public String transactionId ;
            public String getTransactionId(){ return this.transactionId; }
            public void setTransactionId(String transactionId){ this.transactionId = transactionId; }

            public String transactionId(){ return this.transactionId; }
            public PayNotifyRequest transactionId(String transactionId){ this.transactionId = transactionId; return this; }
          
            /**
            *
            **/
            public com.isuwang.dapeng.json.demo.enums.TOrderPayType payType ;
            public com.isuwang.dapeng.json.demo.enums.TOrderPayType getPayType(){ return this.payType; }
            public void setPayType(com.isuwang.dapeng.json.demo.enums.TOrderPayType payType){ this.payType = payType; }

            public com.isuwang.dapeng.json.demo.enums.TOrderPayType payType(){ return this.payType; }
            public PayNotifyRequest payType(com.isuwang.dapeng.json.demo.enums.TOrderPayType payType){ this.payType = payType; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("orderNum").append("\":\"").append(this.orderNum).append("\",");
    stringBuilder.append("\"").append("transactionId").append("\":\"").append(this.transactionId).append("\",");
    stringBuilder.append("\"").append("payType").append("\":").append(this.payType).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      