package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class RecommendItem{
        
            /**
            *

 id

            **/
            public int id ;
            public int getId(){ return this.id; }
            public void setId(int id){ this.id = id; }

            public int id(){ return this.id; }
            public RecommendItem id(int id){ this.id = id; return this; }
          
            /**
            *

 患者id

            **/
            public int patientId ;
            public int getPatientId(){ return this.patientId; }
            public void setPatientId(int patientId){ this.patientId = patientId; }

            public int patientId(){ return this.patientId; }
            public RecommendItem patientId(int patientId){ this.patientId = patientId; return this; }
          
            /**
            *

 订单id

            **/
            public int orderId ;
            public int getOrderId(){ return this.orderId; }
            public void setOrderId(int orderId){ this.orderId = orderId; }

            public int orderId(){ return this.orderId; }
            public RecommendItem orderId(int orderId){ this.orderId = orderId; return this; }
          
            /**
            *

 推荐类型

            **/
            public com.isuwang.dapeng.json.demo.enums.RecommendTypeEnum recommendType ;
            public com.isuwang.dapeng.json.demo.enums.RecommendTypeEnum getRecommendType(){ return this.recommendType; }
            public void setRecommendType(com.isuwang.dapeng.json.demo.enums.RecommendTypeEnum recommendType){ this.recommendType = recommendType; }

            public com.isuwang.dapeng.json.demo.enums.RecommendTypeEnum recommendType(){ return this.recommendType; }
            public RecommendItem recommendType(com.isuwang.dapeng.json.demo.enums.RecommendTypeEnum recommendType){ this.recommendType = recommendType; return this; }
          
            /**
            *

 推荐的医生id

            **/
            public Optional<Integer> recDoctorId = Optional.empty();
            public Optional<Integer> getRecDoctorId(){ return this.recDoctorId; }
            public void setRecDoctorId(Optional<Integer> recDoctorId){ this.recDoctorId = recDoctorId; }

            public Optional<Integer> recDoctorId(){ return this.recDoctorId; }
            public RecommendItem recDoctorId(Optional<Integer> recDoctorId){ this.recDoctorId = recDoctorId; return this; }
          
            /**
            *

 推荐的量表类型

            **/
            public Optional<String> recTitleCategory = Optional.empty();
            public Optional<String> getRecTitleCategory(){ return this.recTitleCategory; }
            public void setRecTitleCategory(Optional<String> recTitleCategory){ this.recTitleCategory = recTitleCategory; }

            public Optional<String> recTitleCategory(){ return this.recTitleCategory; }
            public RecommendItem recTitleCategory(Optional<String> recTitleCategory){ this.recTitleCategory = recTitleCategory; return this; }
          
            /**
            *

 推荐人(医生)id

            **/
            public int recommendBy ;
            public int getRecommendBy(){ return this.recommendBy; }
            public void setRecommendBy(int recommendBy){ this.recommendBy = recommendBy; }

            public int recommendBy(){ return this.recommendBy; }
            public RecommendItem recommendBy(int recommendBy){ this.recommendBy = recommendBy; return this; }
          
            /**
            *

 推荐医生详情

            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.DoctorInfo> recDoctorInfo = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.DoctorInfo> getRecDoctorInfo(){ return this.recDoctorInfo; }
            public void setRecDoctorInfo(Optional<com.isuwang.dapeng.json.demo.domain.DoctorInfo> recDoctorInfo){ this.recDoctorInfo = recDoctorInfo; }

            public Optional<com.isuwang.dapeng.json.demo.domain.DoctorInfo> recDoctorInfo(){ return this.recDoctorInfo; }
            public RecommendItem recDoctorInfo(Optional<com.isuwang.dapeng.json.demo.domain.DoctorInfo> recDoctorInfo){ this.recDoctorInfo = recDoctorInfo; return this; }
          
            /**
            *

 治疗费

            **/
            public Optional<Double> price = Optional.empty();
            public Optional<Double> getPrice(){ return this.price; }
            public void setPrice(Optional<Double> price){ this.price = price; }

            public Optional<Double> price(){ return this.price; }
            public RecommendItem price(Optional<Double> price){ this.price = price; return this; }
          
            /**
            *

 折扣价

            **/
            public Optional<Double> discountPrice = Optional.empty();
            public Optional<Double> getDiscountPrice(){ return this.discountPrice; }
            public void setDiscountPrice(Optional<Double> discountPrice){ this.discountPrice = discountPrice; }

            public Optional<Double> discountPrice(){ return this.discountPrice; }
            public RecommendItem discountPrice(Optional<Double> discountPrice){ this.discountPrice = discountPrice; return this; }
          
            /**
            *

 单位可治疗时间(分钟)

            **/
            public Optional<Integer> unitTime = Optional.empty();
            public Optional<Integer> getUnitTime(){ return this.unitTime; }
            public void setUnitTime(Optional<Integer> unitTime){ this.unitTime = unitTime; }

            public Optional<Integer> unitTime(){ return this.unitTime; }
            public RecommendItem unitTime(Optional<Integer> unitTime){ this.unitTime = unitTime; return this; }
          
            /**
            *

 最近是否可预约

            **/
            public Optional<Boolean> isWorkable = Optional.empty();
            public Optional<Boolean> getIsWorkable(){ return this.isWorkable; }
            public void setIsWorkable(Optional<Boolean> isWorkable){ this.isWorkable = isWorkable; }

            public Optional<Boolean> isWorkable(){ return this.isWorkable; }
            public RecommendItem isWorkable(Optional<Boolean> isWorkable){ this.isWorkable = isWorkable; return this; }
          
            /**
            *

 量表详情

            **/
            public Optional<com.isuwang.dapeng.json.demo.domain.TitleCategoryInfo> titleCategoryInfo = Optional.empty();
            public Optional<com.isuwang.dapeng.json.demo.domain.TitleCategoryInfo> getTitleCategoryInfo(){ return this.titleCategoryInfo; }
            public void setTitleCategoryInfo(Optional<com.isuwang.dapeng.json.demo.domain.TitleCategoryInfo> titleCategoryInfo){ this.titleCategoryInfo = titleCategoryInfo; }

            public Optional<com.isuwang.dapeng.json.demo.domain.TitleCategoryInfo> titleCategoryInfo(){ return this.titleCategoryInfo; }
            public RecommendItem titleCategoryInfo(Optional<com.isuwang.dapeng.json.demo.domain.TitleCategoryInfo> titleCategoryInfo){ this.titleCategoryInfo = titleCategoryInfo; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":").append(this.id).append(",");
    stringBuilder.append("\"").append("patientId").append("\":").append(this.patientId).append(",");
    stringBuilder.append("\"").append("orderId").append("\":").append(this.orderId).append(",");
    stringBuilder.append("\"").append("recommendType").append("\":").append(this.recommendType).append(",");
    stringBuilder.append("\"").append("recDoctorId").append("\":").append(this.recDoctorId.isPresent()?this.recDoctorId.get():null).append(",");
    stringBuilder.append("\"").append("recTitleCategory").append("\":\"").append(this.recTitleCategory.isPresent()?this.recTitleCategory.get():null).append("\",");
    stringBuilder.append("\"").append("recommendBy").append("\":").append(this.recommendBy).append(",");
    stringBuilder.append("\"").append("recDoctorInfo").append("\":").append(this.recDoctorInfo.isPresent()?this.recDoctorInfo.get().toString():null).append(",");
    stringBuilder.append("\"").append("price").append("\":").append(this.price.isPresent()?this.price.get():null).append(",");
    stringBuilder.append("\"").append("discountPrice").append("\":").append(this.discountPrice.isPresent()?this.discountPrice.get():null).append(",");
    stringBuilder.append("\"").append("unitTime").append("\":").append(this.unitTime.isPresent()?this.unitTime.get():null).append(",");
    stringBuilder.append("\"").append("isWorkable").append("\":").append(this.isWorkable.isPresent()?this.isWorkable.get():null).append(",");
    stringBuilder.append("\"").append("titleCategoryInfo").append("\":").append(this.titleCategoryInfo.isPresent()?this.titleCategoryInfo.get().toString():null).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      