package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class SliderNoticeItem{
        
            /**
            *

 用户手机号

            **/
            public String patientPhone ;
            public String getPatientPhone(){ return this.patientPhone; }
            public void setPatientPhone(String patientPhone){ this.patientPhone = patientPhone; }

            public String patientPhone(){ return this.patientPhone; }
            public SliderNoticeItem patientPhone(String patientPhone){ this.patientPhone = patientPhone; return this; }
          
            /**
            *

 通知类型

            **/
            public com.isuwang.dapeng.json.demo.enums.SliderNoticeType sliderNoticeType ;
            public com.isuwang.dapeng.json.demo.enums.SliderNoticeType getSliderNoticeType(){ return this.sliderNoticeType; }
            public void setSliderNoticeType(com.isuwang.dapeng.json.demo.enums.SliderNoticeType sliderNoticeType){ this.sliderNoticeType = sliderNoticeType; }

            public com.isuwang.dapeng.json.demo.enums.SliderNoticeType sliderNoticeType(){ return this.sliderNoticeType; }
            public SliderNoticeItem sliderNoticeType(com.isuwang.dapeng.json.demo.enums.SliderNoticeType sliderNoticeType){ this.sliderNoticeType = sliderNoticeType; return this; }
          
            /**
            *

 医生姓名

            **/
            public Optional<String> doctorName = Optional.empty();
            public Optional<String> getDoctorName(){ return this.doctorName; }
            public void setDoctorName(Optional<String> doctorName){ this.doctorName = doctorName; }

            public Optional<String> doctorName(){ return this.doctorName; }
            public SliderNoticeItem doctorName(Optional<String> doctorName){ this.doctorName = doctorName; return this; }
          
            /**
            *

 量表名称

            **/
            public Optional<String> titleName = Optional.empty();
            public Optional<String> getTitleName(){ return this.titleName; }
            public void setTitleName(Optional<String> titleName){ this.titleName = titleName; }

            public Optional<String> titleName(){ return this.titleName; }
            public SliderNoticeItem titleName(Optional<String> titleName){ this.titleName = titleName; return this; }
          
            /**
            *

 通知时间

            **/
            public long createdAt ;
            public long getCreatedAt(){ return this.createdAt; }
            public void setCreatedAt(long createdAt){ this.createdAt = createdAt; }

            public long createdAt(){ return this.createdAt; }
            public SliderNoticeItem createdAt(long createdAt){ this.createdAt = createdAt; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("patientPhone").append("\":\"").append(this.patientPhone).append("\",");
    stringBuilder.append("\"").append("sliderNoticeType").append("\":").append(this.sliderNoticeType).append(",");
    stringBuilder.append("\"").append("doctorName").append("\":\"").append(this.doctorName.isPresent()?this.doctorName.get():null).append("\",");
    stringBuilder.append("\"").append("titleName").append("\":\"").append(this.titleName.isPresent()?this.titleName.get():null).append("\",");
    stringBuilder.append("\"").append("createdAt").append("\":").append(this.createdAt).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      