package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TAppointmentDTO{
        
            /**
            *

 排班ID

            **/
            public int id ;
            public int getId(){ return this.id; }
            public void setId(int id){ this.id = id; }

            public int id(){ return this.id; }
            public TAppointmentDTO id(int id){ this.id = id; return this; }
          
            /**
            *

 医生 ID

            **/
            public int doctorId ;
            public int getDoctorId(){ return this.doctorId; }
            public void setDoctorId(int doctorId){ this.doctorId = doctorId; }

            public int doctorId(){ return this.doctorId; }
            public TAppointmentDTO doctorId(int doctorId){ this.doctorId = doctorId; return this; }
          
            /**
            *

 医生等级

            **/
            public int level ;
            public int getLevel(){ return this.level; }
            public void setLevel(int level){ this.level = level; }

            public int level(){ return this.level; }
            public TAppointmentDTO level(int level){ this.level = level; return this; }
          
            /**
            *

  医生可预约开始时间

            **/
            public long appointmentBeginTime ;
            public long getAppointmentBeginTime(){ return this.appointmentBeginTime; }
            public void setAppointmentBeginTime(long appointmentBeginTime){ this.appointmentBeginTime = appointmentBeginTime; }

            public long appointmentBeginTime(){ return this.appointmentBeginTime; }
            public TAppointmentDTO appointmentBeginTime(long appointmentBeginTime){ this.appointmentBeginTime = appointmentBeginTime; return this; }
          
            /**
            *

  医生可预约开始时间

            **/
            public long appointmentEndTime ;
            public long getAppointmentEndTime(){ return this.appointmentEndTime; }
            public void setAppointmentEndTime(long appointmentEndTime){ this.appointmentEndTime = appointmentEndTime; }

            public long appointmentEndTime(){ return this.appointmentEndTime; }
            public TAppointmentDTO appointmentEndTime(long appointmentEndTime){ this.appointmentEndTime = appointmentEndTime; return this; }
          
            /**
            *

 挂号费用

            **/
            public double registrationAmount ;
            public double getRegistrationAmount(){ return this.registrationAmount; }
            public void setRegistrationAmount(double registrationAmount){ this.registrationAmount = registrationAmount; }

            public double registrationAmount(){ return this.registrationAmount; }
            public TAppointmentDTO registrationAmount(double registrationAmount){ this.registrationAmount = registrationAmount; return this; }
          
            /**
            *

 挂号费用

            **/
            public double discountRegistrationAmount ;
            public double getDiscountRegistrationAmount(){ return this.discountRegistrationAmount; }
            public void setDiscountRegistrationAmount(double discountRegistrationAmount){ this.discountRegistrationAmount = discountRegistrationAmount; }

            public double discountRegistrationAmount(){ return this.discountRegistrationAmount; }
            public TAppointmentDTO discountRegistrationAmount(double discountRegistrationAmount){ this.discountRegistrationAmount = discountRegistrationAmount; return this; }
          
            /**
            *

 预约状态,1:可领取[医生可以排班的](available);2:可预约(workable);3:已预约(reserved);4:已过期[当天没人预约就置为过期](refund)

            **/
            public int status ;
            public int getStatus(){ return this.status; }
            public void setStatus(int status){ this.status = status; }

            public int status(){ return this.status; }
            public TAppointmentDTO status(int status){ this.status = status; return this; }
          
            /**
            *

 创建时间

            **/
            public long createdAt ;
            public long getCreatedAt(){ return this.createdAt; }
            public void setCreatedAt(long createdAt){ this.createdAt = createdAt; }

            public long createdAt(){ return this.createdAt; }
            public TAppointmentDTO createdAt(long createdAt){ this.createdAt = createdAt; return this; }
          
            /**
            *



            **/
            public int createdBy ;
            public int getCreatedBy(){ return this.createdBy; }
            public void setCreatedBy(int createdBy){ this.createdBy = createdBy; }

            public int createdBy(){ return this.createdBy; }
            public TAppointmentDTO createdBy(int createdBy){ this.createdBy = createdBy; return this; }
          
            /**
            *

 更新时间

            **/
            public long updatedAt ;
            public long getUpdatedAt(){ return this.updatedAt; }
            public void setUpdatedAt(long updatedAt){ this.updatedAt = updatedAt; }

            public long updatedAt(){ return this.updatedAt; }
            public TAppointmentDTO updatedAt(long updatedAt){ this.updatedAt = updatedAt; return this; }
          
            /**
            *



            **/
            public int updatedBy ;
            public int getUpdatedBy(){ return this.updatedBy; }
            public void setUpdatedBy(int updatedBy){ this.updatedBy = updatedBy; }

            public int updatedBy(){ return this.updatedBy; }
            public TAppointmentDTO updatedBy(int updatedBy){ this.updatedBy = updatedBy; return this; }
          
            /**
            *



            **/
            public String remark ;
            public String getRemark(){ return this.remark; }
            public void setRemark(String remark){ this.remark = remark; }

            public String remark(){ return this.remark; }
            public TAppointmentDTO remark(String remark){ this.remark = remark; return this; }
          
            /**
            *

排班时间id

            **/
            public int appointmentTimeId ;
            public int getAppointmentTimeId(){ return this.appointmentTimeId; }
            public void setAppointmentTimeId(int appointmentTimeId){ this.appointmentTimeId = appointmentTimeId; }

            public int appointmentTimeId(){ return this.appointmentTimeId; }
            public TAppointmentDTO appointmentTimeId(int appointmentTimeId){ this.appointmentTimeId = appointmentTimeId; return this; }
          
            /**
            *

 排班类型,1:首诊(first_visit);2:复诊(return_visit);3:预约治疗(treat)

            **/
            public int appointmentType ;
            public int getAppointmentType(){ return this.appointmentType; }
            public void setAppointmentType(int appointmentType){ this.appointmentType = appointmentType; }

            public int appointmentType(){ return this.appointmentType; }
            public TAppointmentDTO appointmentType(int appointmentType){ this.appointmentType = appointmentType; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":").append(this.id).append(",");
    stringBuilder.append("\"").append("doctorId").append("\":").append(this.doctorId).append(",");
    stringBuilder.append("\"").append("level").append("\":").append(this.level).append(",");
    stringBuilder.append("\"").append("appointmentBeginTime").append("\":").append(this.appointmentBeginTime).append(",");
    stringBuilder.append("\"").append("appointmentEndTime").append("\":").append(this.appointmentEndTime).append(",");
    stringBuilder.append("\"").append("registrationAmount").append("\":").append(this.registrationAmount).append(",");
    stringBuilder.append("\"").append("discountRegistrationAmount").append("\":").append(this.discountRegistrationAmount).append(",");
    stringBuilder.append("\"").append("status").append("\":").append(this.status).append(",");
    stringBuilder.append("\"").append("createdAt").append("\":").append(this.createdAt).append(",");
    stringBuilder.append("\"").append("createdBy").append("\":").append(this.createdBy).append(",");
    stringBuilder.append("\"").append("updatedAt").append("\":").append(this.updatedAt).append(",");
    stringBuilder.append("\"").append("updatedBy").append("\":").append(this.updatedBy).append(",");
    stringBuilder.append("\"").append("remark").append("\":\"").append(this.remark).append("\",");
    stringBuilder.append("\"").append("appointmentTimeId").append("\":").append(this.appointmentTimeId).append(",");
    stringBuilder.append("\"").append("appointmentType").append("\":").append(this.appointmentType).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      