package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TCouponDTO{
        
            /**
            *



            **/
            public int id ;
            public int getId(){ return this.id; }
            public void setId(int id){ this.id = id; }

            public int id(){ return this.id; }
            public TCouponDTO id(int id){ this.id = id; return this; }
          
            /**
            *

订单id

            **/
            public Optional<Integer> orderId = Optional.empty();
            public Optional<Integer> getOrderId(){ return this.orderId; }
            public void setOrderId(Optional<Integer> orderId){ this.orderId = orderId; }

            public Optional<Integer> orderId(){ return this.orderId; }
            public TCouponDTO orderId(Optional<Integer> orderId){ this.orderId = orderId; return this; }
          
            /**
            *

 优惠券类型,1:优惠券(discount);2:心理咨询优惠券[仅限于预约心理咨询](appointment)

            **/
            public com.isuwang.dapeng.json.demo.enums.TCouponType type ;
            public com.isuwang.dapeng.json.demo.enums.TCouponType getType(){ return this.type; }
            public void setType(com.isuwang.dapeng.json.demo.enums.TCouponType type){ this.type = type; }

            public com.isuwang.dapeng.json.demo.enums.TCouponType type(){ return this.type; }
            public TCouponDTO type(com.isuwang.dapeng.json.demo.enums.TCouponType type){ this.type = type; return this; }
          
            /**
            *

 优惠券面值

            **/
            public double amount ;
            public double getAmount(){ return this.amount; }
            public void setAmount(double amount){ this.amount = amount; }

            public double amount(){ return this.amount; }
            public TCouponDTO amount(double amount){ this.amount = amount; return this; }
          
            /**
            *

 发行时间

            **/
            public long publishAt ;
            public long getPublishAt(){ return this.publishAt; }
            public void setPublishAt(long publishAt){ this.publishAt = publishAt; }

            public long publishAt(){ return this.publishAt; }
            public TCouponDTO publishAt(long publishAt){ this.publishAt = publishAt; return this; }
          
            /**
            *

 过期时间

            **/
            public long expiredAt ;
            public long getExpiredAt(){ return this.expiredAt; }
            public void setExpiredAt(long expiredAt){ this.expiredAt = expiredAt; }

            public long expiredAt(){ return this.expiredAt; }
            public TCouponDTO expiredAt(long expiredAt){ this.expiredAt = expiredAt; return this; }
          
            /**
            *

 患者id

            **/
            public Optional<Integer> patientId = Optional.empty();
            public Optional<Integer> getPatientId(){ return this.patientId; }
            public void setPatientId(Optional<Integer> patientId){ this.patientId = patientId; }

            public Optional<Integer> patientId(){ return this.patientId; }
            public TCouponDTO patientId(Optional<Integer> patientId){ this.patientId = patientId; return this; }
          
            /**
            *

 状态,0:无效(invalid);1:新发(available);2:已使用(used);3:已过期(expired)

            **/
            public com.isuwang.dapeng.json.demo.enums.TCouponStatus status ;
            public com.isuwang.dapeng.json.demo.enums.TCouponStatus getStatus(){ return this.status; }
            public void setStatus(com.isuwang.dapeng.json.demo.enums.TCouponStatus status){ this.status = status; }

            public com.isuwang.dapeng.json.demo.enums.TCouponStatus status(){ return this.status; }
            public TCouponDTO status(com.isuwang.dapeng.json.demo.enums.TCouponStatus status){ this.status = status; return this; }
          
            /**
            *



            **/
            public long createdAt ;
            public long getCreatedAt(){ return this.createdAt; }
            public void setCreatedAt(long createdAt){ this.createdAt = createdAt; }

            public long createdAt(){ return this.createdAt; }
            public TCouponDTO createdAt(long createdAt){ this.createdAt = createdAt; return this; }
          
            /**
            *



            **/
            public int createdBy ;
            public int getCreatedBy(){ return this.createdBy; }
            public void setCreatedBy(int createdBy){ this.createdBy = createdBy; }

            public int createdBy(){ return this.createdBy; }
            public TCouponDTO createdBy(int createdBy){ this.createdBy = createdBy; return this; }
          
            /**
            *



            **/
            public long updatedAt ;
            public long getUpdatedAt(){ return this.updatedAt; }
            public void setUpdatedAt(long updatedAt){ this.updatedAt = updatedAt; }

            public long updatedAt(){ return this.updatedAt; }
            public TCouponDTO updatedAt(long updatedAt){ this.updatedAt = updatedAt; return this; }
          
            /**
            *



            **/
            public int updatedBy ;
            public int getUpdatedBy(){ return this.updatedBy; }
            public void setUpdatedBy(int updatedBy){ this.updatedBy = updatedBy; }

            public int updatedBy(){ return this.updatedBy; }
            public TCouponDTO updatedBy(int updatedBy){ this.updatedBy = updatedBy; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("id").append("\":").append(this.id).append(",");
    stringBuilder.append("\"").append("orderId").append("\":").append(this.orderId.isPresent()?this.orderId.get():null).append(",");
    stringBuilder.append("\"").append("type").append("\":").append(this.type).append(",");
    stringBuilder.append("\"").append("amount").append("\":").append(this.amount).append(",");
    stringBuilder.append("\"").append("publishAt").append("\":").append(this.publishAt).append(",");
    stringBuilder.append("\"").append("expiredAt").append("\":").append(this.expiredAt).append(",");
    stringBuilder.append("\"").append("patientId").append("\":").append(this.patientId.isPresent()?this.patientId.get():null).append(",");
    stringBuilder.append("\"").append("status").append("\":").append(this.status).append(",");
    stringBuilder.append("\"").append("createdAt").append("\":").append(this.createdAt).append(",");
    stringBuilder.append("\"").append("createdBy").append("\":").append(this.createdBy).append(",");
    stringBuilder.append("\"").append("updatedAt").append("\":").append(this.updatedAt).append(",");
    stringBuilder.append("\"").append("updatedBy").append("\":").append(this.updatedBy).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      