package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 评测量表信息 
        **/
        public class TitleCategoryInfo{
        
            /**
            *

 评测量表类型

            **/
            public String category ;
            public String getCategory(){ return this.category; }
            public void setCategory(String category){ this.category = category; }

            public String category(){ return this.category; }
            public TitleCategoryInfo category(String category){ this.category = category; return this; }
          
            /**
            *

 量表中文名

            **/
            public String name ;
            public String getName(){ return this.name; }
            public void setName(String name){ this.name = name; }

            public String name(){ return this.name; }
            public TitleCategoryInfo name(String name){ this.name = name; return this; }
          
            /**
            *

 对应患症标签空格分割

            **/
            public Optional<String> labels = Optional.empty();
            public Optional<String> getLabels(){ return this.labels; }
            public void setLabels(Optional<String> labels){ this.labels = labels; }

            public Optional<String> labels(){ return this.labels; }
            public TitleCategoryInfo labels(Optional<String> labels){ this.labels = labels; return this; }
          
            /**
            *

 描述

            **/
            public Optional<String> desc = Optional.empty();
            public Optional<String> getDesc(){ return this.desc; }
            public void setDesc(Optional<String> desc){ this.desc = desc; }

            public Optional<String> desc(){ return this.desc; }
            public TitleCategoryInfo desc(Optional<String> desc){ this.desc = desc; return this; }
          
            /**
            *

 测试次数

            **/
            public Optional<Integer> testCount = Optional.empty();
            public Optional<Integer> getTestCount(){ return this.testCount; }
            public void setTestCount(Optional<Integer> testCount){ this.testCount = testCount; }

            public Optional<Integer> testCount(){ return this.testCount; }
            public TitleCategoryInfo testCount(Optional<Integer> testCount){ this.testCount = testCount; return this; }
          
            /**
            *

 备注

            **/
            public Optional<String> remark = Optional.empty();
            public Optional<String> getRemark(){ return this.remark; }
            public void setRemark(Optional<String> remark){ this.remark = remark; }

            public Optional<String> remark(){ return this.remark; }
            public TitleCategoryInfo remark(Optional<String> remark){ this.remark = remark; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("category").append("\":\"").append(this.category).append("\",");
    stringBuilder.append("\"").append("name").append("\":\"").append(this.name).append("\",");
    stringBuilder.append("\"").append("labels").append("\":\"").append(this.labels.isPresent()?this.labels.get():null).append("\",");
    stringBuilder.append("\"").append("desc").append("\":\"").append(this.desc.isPresent()?this.desc.get():null).append("\",");
    stringBuilder.append("\"").append("testCount").append("\":").append(this.testCount.isPresent()?this.testCount.get():null).append(",");
    stringBuilder.append("\"").append("remark").append("\":\"").append(this.remark.isPresent()?this.remark.get():null).append("\",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      