package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TPriceRuleDTO{
        
            /**
            *医生等级
            **/
            public int level ;
            public int getLevel(){ return this.level; }
            public void setLevel(int level){ this.level = level; }

            public int level(){ return this.level; }
            public TPriceRuleDTO level(int level){ this.level = level; return this; }
          
            /**
            *医院Id
            **/
            public int hospitalId ;
            public int getHospitalId(){ return this.hospitalId; }
            public void setHospitalId(int hospitalId){ this.hospitalId = hospitalId; }

            public int hospitalId(){ return this.hospitalId; }
            public TPriceRuleDTO hospitalId(int hospitalId){ this.hospitalId = hospitalId; return this; }
          
            /**
            *排班类型
            **/
            public com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType ;
            public com.isuwang.dapeng.json.demo.enums.AppointmentType getAppointmentType(){ return this.appointmentType; }
            public void setAppointmentType(com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType){ this.appointmentType = appointmentType; }

            public com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType(){ return this.appointmentType; }
            public TPriceRuleDTO appointmentType(com.isuwang.dapeng.json.demo.enums.AppointmentType appointmentType){ this.appointmentType = appointmentType; return this; }
          
            /**
            *价格
            **/
            public double price ;
            public double getPrice(){ return this.price; }
            public void setPrice(double price){ this.price = price; }

            public double price(){ return this.price; }
            public TPriceRuleDTO price(double price){ this.price = price; return this; }
          
            /**
            *折扣价
            **/
            public double discountPrice ;
            public double getDiscountPrice(){ return this.discountPrice; }
            public void setDiscountPrice(double discountPrice){ this.discountPrice = discountPrice; }

            public double discountPrice(){ return this.discountPrice; }
            public TPriceRuleDTO discountPrice(double discountPrice){ this.discountPrice = discountPrice; return this; }
          
            /**
            *备注
            **/
            public Optional<String> remark = Optional.empty();
            public Optional<String> getRemark(){ return this.remark; }
            public void setRemark(Optional<String> remark){ this.remark = remark; }

            public Optional<String> remark(){ return this.remark; }
            public TPriceRuleDTO remark(Optional<String> remark){ this.remark = remark; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("level").append("\":").append(this.level).append(",");
    stringBuilder.append("\"").append("hospitalId").append("\":").append(this.hospitalId).append(",");
    stringBuilder.append("\"").append("appointmentType").append("\":").append(this.appointmentType).append(",");
    stringBuilder.append("\"").append("price").append("\":").append(this.price).append(",");
    stringBuilder.append("\"").append("discountPrice").append("\":").append(this.discountPrice).append(",");
    stringBuilder.append("\"").append("remark").append("\":\"").append(this.remark.isPresent()?this.remark.get():null).append("\",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      