package com.isuwang.dapeng.json.demo.domain;

        import java.util.Optional;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *
        **/
        public class TreatPlanItem{
        
            /**
            *

  orderId

            **/
            public int orderId ;
            public int getOrderId(){ return this.orderId; }
            public void setOrderId(int orderId){ this.orderId = orderId; }

            public int orderId(){ return this.orderId; }
            public TreatPlanItem orderId(int orderId){ this.orderId = orderId; return this; }
          
            /**
            *

  doctorId

            **/
            public int doctorId ;
            public int getDoctorId(){ return this.doctorId; }
            public void setDoctorId(int doctorId){ this.doctorId = doctorId; }

            public int doctorId(){ return this.doctorId; }
            public TreatPlanItem doctorId(int doctorId){ this.doctorId = doctorId; return this; }
          
            /**
            *

  医生名字

            **/
            public String doctorName ;
            public String getDoctorName(){ return this.doctorName; }
            public void setDoctorName(String doctorName){ this.doctorName = doctorName; }

            public String doctorName(){ return this.doctorName; }
            public TreatPlanItem doctorName(String doctorName){ this.doctorName = doctorName; return this; }
          
            /**
            *

  治疗开始时间

            **/
            public long therapyBeginTime ;
            public long getTherapyBeginTime(){ return this.therapyBeginTime; }
            public void setTherapyBeginTime(long therapyBeginTime){ this.therapyBeginTime = therapyBeginTime; }

            public long therapyBeginTime(){ return this.therapyBeginTime; }
            public TreatPlanItem therapyBeginTime(long therapyBeginTime){ this.therapyBeginTime = therapyBeginTime; return this; }
          
            /**
            *

  治疗时间

            **/
            public long therapyEndTime ;
            public long getTherapyEndTime(){ return this.therapyEndTime; }
            public void setTherapyEndTime(long therapyEndTime){ this.therapyEndTime = therapyEndTime; }

            public long therapyEndTime(){ return this.therapyEndTime; }
            public TreatPlanItem therapyEndTime(long therapyEndTime){ this.therapyEndTime = therapyEndTime; return this; }
          
            /**
            *

  剩余秒数

            **/
            public Optional<Long> remainSeconds = Optional.empty();
            public Optional<Long> getRemainSeconds(){ return this.remainSeconds; }
            public void setRemainSeconds(Optional<Long> remainSeconds){ this.remainSeconds = remainSeconds; }

            public Optional<Long> remainSeconds(){ return this.remainSeconds; }
            public TreatPlanItem remainSeconds(Optional<Long> remainSeconds){ this.remainSeconds = remainSeconds; return this; }
          
            /**
            *

  剩余秒数

            **/
            public com.isuwang.dapeng.json.demo.enums.TOrderStatus status ;
            public com.isuwang.dapeng.json.demo.enums.TOrderStatus getStatus(){ return this.status; }
            public void setStatus(com.isuwang.dapeng.json.demo.enums.TOrderStatus status){ this.status = status; }

            public com.isuwang.dapeng.json.demo.enums.TOrderStatus status(){ return this.status; }
            public TreatPlanItem status(com.isuwang.dapeng.json.demo.enums.TOrderStatus status){ this.status = status; return this; }
          

        public String toString(){
          StringBuilder stringBuilder = new StringBuilder("{");
          stringBuilder.append("\"").append("orderId").append("\":").append(this.orderId).append(",");
    stringBuilder.append("\"").append("doctorId").append("\":").append(this.doctorId).append(",");
    stringBuilder.append("\"").append("doctorName").append("\":\"").append(this.doctorName).append("\",");
    stringBuilder.append("\"").append("therapyBeginTime").append("\":").append(this.therapyBeginTime).append(",");
    stringBuilder.append("\"").append("therapyEndTime").append("\":").append(this.therapyEndTime).append(",");
    stringBuilder.append("\"").append("remainSeconds").append("\":").append(this.remainSeconds.isPresent()?this.remainSeconds.get():null).append(",");
    stringBuilder.append("\"").append("status").append("\":").append(this.status).append(",");
    
          stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
          stringBuilder.append("}");

          return stringBuilder.toString();
        }
      }
      