
      package com.isuwang.soa.price.service;

      import com.isuwang.dapeng.core.Processor;
      import com.isuwang.dapeng.core.Service;
      import com.isuwang.dapeng.core.SoaGlobalTransactional;

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      * 
      **/
      @Service(name="com.isuwang.soa.price.service.PriceService",version = "1.0.0")
      @Processor(className = "com.isuwang.soa.price.PriceServiceCodec$Processor")
      public interface PriceService {
      
          /**
          * 
          **/
          
             
             void insertPrice( com.isuwang.soa.price.domain.Price price) throws com.isuwang.dapeng.core.SoaException;
            
        
          /**
          * 
          **/
          
             
             java.util.List<com.isuwang.soa.price.domain.Price> getPrices() throws com.isuwang.dapeng.core.SoaException;
            
        
      }
      