package com.isuwang.soa.scala

import com.isuwang.dapeng.core._;
        import com.isuwang.org.apache.thrift._;
        import java.util.ServiceLoader;
        import java.util.concurrent.CompletableFuture;
        import com.isuwang.soa.scala.PrintServiceAsyncCodec._;
        import com.isuwang.soa.scala.service.PrintServiceAsync;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        **/
        class PrintServiceAsyncClient extends PrintServiceAsync {

        import java.util.function.{ Function ⇒ JFunction, Predicate ⇒ JPredicate, BiPredicate }
        implicit def toJavaFunction[A, B](f: Function1[A, B]) = new JFunction[A, B] {
          override def apply(a: A): B = f(a)
        }

        val serviceName = "com.isuwang.soa.scala.service.PrintService"
        val version = "1.0.0"
        val pool = {
          val serviceLoader = ServiceLoader.load(classOf[SoaConnectionPoolFactory])
          if (serviceLoader.iterator().hasNext) {
            val poolImpl = serviceLoader.iterator().next().getPool
            poolImpl.registerClientInfo(serviceName,version)
            poolImpl
          } else null
        }

        def getServiceMetadata: String = {
          pool.send(
          serviceName,
          version,
          "getServiceMetadata",
          new getServiceMetadata_args,
          new GetServiceMetadata_argsSerializer,
          new GetServiceMetadata_resultSerializer
          ).success
        }


        

            /**
            * 
            **/
            def print(
             timeout: Long = 5000) : Unit = {

            val response = pool.sendAsync(
            serviceName,
            version,
            "print",
            print_args(),
            new Print_argsSerializer(),
            new Print_resultSerializer()
            ,timeout).asInstanceOf[CompletableFuture[print_result]]

            

          }

          

            /**
            * 
            **/
            def printInfo(info:com.isuwang.soa.scala.info.Info 
            , timeout: Long = 5000) : String = {

            val response = pool.sendAsync(
            serviceName,
            version,
            "printInfo",
            printInfo_args(info),
            new PrintInfo_argsSerializer(),
            new PrintInfo_resultSerializer()
            ,timeout).asInstanceOf[CompletableFuture[printInfo_result]]

            response.thenApply(_.success).get

          }

          

            /**
            * 
            **/
            def printInfo2(name:String 
            , timeout: Long = 5000) : String = {

            val response = pool.sendAsync(
            serviceName,
            version,
            "printInfo2",
            printInfo2_args(name),
            new PrintInfo2_argsSerializer(),
            new PrintInfo2_resultSerializer()
            ,timeout).asInstanceOf[CompletableFuture[printInfo2_result]]

            response.thenApply(_.success).get

          }

          

            /**
            * 
            **/
            def printInfo3(accountType:com.isuwang.soa.scala.account.scala.enums.AccountType 
            , timeout: Long = 5000) : String = {

            val response = pool.sendAsync(
            serviceName,
            version,
            "printInfo3",
            printInfo3_args(accountType),
            new PrintInfo3_argsSerializer(),
            new PrintInfo3_resultSerializer()
            ,timeout).asInstanceOf[CompletableFuture[printInfo3_result]]

            response.thenApply(_.success).get

          }

          
      }
      