 package com.isuwang.dapeng.json.demo.domain.serializer;
        import com.isuwang.dapeng.json.demo.domain.serializer.*;

        import com.isuwang.dapeng.core.*;
        import com.isuwang.org.apache.thrift.*;
        import com.isuwang.org.apache.thrift.protocol.*;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;

        /**
        * Autogenerated by Dapeng-Code-Generator (1.2.2)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *  @generated
        **/
        public class ListOrderResponseSerializer implements BeanSerializer<com.isuwang.dapeng.json.demo.domain.ListOrderResponse>{
        
      @Override
      public com.isuwang.dapeng.json.demo.domain.ListOrderResponse read(TProtocol iprot) throws TException{

      com.isuwang.dapeng.json.demo.domain.ListOrderResponse bean = new com.isuwang.dapeng.json.demo.domain.ListOrderResponse();
      com.isuwang.org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();

      while(true){
        schemeField = iprot.readFieldBegin();
        if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.STOP){ break;}

        switch(schemeField.id){
          
              case 1:
              if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.LIST){
               com.isuwang.org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
        java.util.List<com.isuwang.dapeng.json.demo.domain.OrderItem> elem0 = new java.util.ArrayList<>(_list0.size);
        for(int _i0 = 0; _i0 < _list0.size; ++ _i0){
          com.isuwang.dapeng.json.demo.domain.OrderItem elem1 = new com.isuwang.dapeng.json.demo.domain.OrderItem();
        elem1=new com.isuwang.dapeng.json.demo.domain.serializer.OrderItemSerializer().read(iprot);
          elem0.add(elem1);
        }
        iprot.readListEnd();
       bean.setOrders(elem0);
            }else{
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 2:
              if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.STRUCT){
              com.isuwang.dapeng.json.demo.domain.PageResponse elem0 = new com.isuwang.dapeng.json.demo.domain.PageResponse();
        elem0=new com.isuwang.dapeng.json.demo.domain.serializer.PageResponseSerializer().read(iprot);
       bean.setPageResponse(elem0);
            }else{
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 3:
              if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.DOUBLE){
               double elem0 = iprot.readDouble();
       bean.setSumAmount(elem0);
            }else{
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 4:
              if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.DOUBLE){
               double elem0 = iprot.readDouble();
       bean.setSumOffLineAmount(elem0);
            }else{
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
          
            default:
            com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      validate(bean);
      return bean;
    }
    
      @Override
      public void write(com.isuwang.dapeng.json.demo.domain.ListOrderResponse bean, TProtocol oprot) throws TException{

      validate(bean);
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("ListOrderResponse"));

      
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("orders", com.isuwang.org.apache.thrift.protocol.TType.LIST, (short) 1));
            java.util.List<com.isuwang.dapeng.json.demo.domain.OrderItem> elem0 = bean.getOrders();
            
          oprot.writeListBegin(new com.isuwang.org.apache.thrift.protocol.TList(com.isuwang.org.apache.thrift.protocol.TType.STRUCT, elem0.size()));
          for(com.isuwang.dapeng.json.demo.domain.OrderItem elem1 : elem0){
           new com.isuwang.dapeng.json.demo.domain.serializer.OrderItemSerializer().write(elem1, oprot);
        }
          oprot.writeListEnd();
        
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("pageResponse", com.isuwang.org.apache.thrift.protocol.TType.STRUCT, (short) 2));
            com.isuwang.dapeng.json.demo.domain.PageResponse elem1 = bean.getPageResponse();
             new com.isuwang.dapeng.json.demo.domain.serializer.PageResponseSerializer().write(elem1, oprot);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("sumAmount", com.isuwang.org.apache.thrift.protocol.TType.DOUBLE, (short) 3));
            Double elem2 = bean.getSumAmount();
            oprot.writeDouble(elem2);
            
            oprot.writeFieldEnd();
          
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("sumOffLineAmount", com.isuwang.org.apache.thrift.protocol.TType.DOUBLE, (short) 4));
            Double elem3 = bean.getSumOffLineAmount();
            oprot.writeDouble(elem3);
            
            oprot.writeFieldEnd();
          
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
      public void validate(com.isuwang.dapeng.json.demo.domain.ListOrderResponse bean) throws TException{
      
              if(bean.getOrders() == null)
              throw new SoaException(SoaBaseCode.NotNull, "orders字段不允许为空");
            
              if(bean.getPageResponse() == null)
              throw new SoaException(SoaBaseCode.NotNull, "pageResponse字段不允许为空");
            
                if(bean.getPageResponse() != null)
                new com.isuwang.dapeng.json.demo.domain.serializer.PageResponseSerializer().validate(bean.getPageResponse());
              
    }
    
        @Override
        public String toString(com.isuwang.dapeng.json.demo.domain.ListOrderResponse bean)
        {return bean == null ? "null" : bean.toString();}
      }
      

      