 package com.isuwang.dapeng.json.demo.domain.serializer;
        import com.isuwang.dapeng.json.demo.domain.serializer.*;

        import com.isuwang.dapeng.core.*;
        import com.isuwang.org.apache.thrift.*;
        import com.isuwang.org.apache.thrift.protocol.*;

        import java.util.Optional;
        import java.util.concurrent.CompletableFuture;
        import java.util.concurrent.Future;

        /**
        * Autogenerated by Dapeng-Code-Generator (1.2.2)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *  @generated
        **/
        public class ListPriceRuleRequestSerializer implements BeanSerializer<com.isuwang.dapeng.json.demo.domain.ListPriceRuleRequest>{
        
      @Override
      public com.isuwang.dapeng.json.demo.domain.ListPriceRuleRequest read(TProtocol iprot) throws TException{

      com.isuwang.dapeng.json.demo.domain.ListPriceRuleRequest bean = new com.isuwang.dapeng.json.demo.domain.ListPriceRuleRequest();
      com.isuwang.org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();

      while(true){
        schemeField = iprot.readFieldBegin();
        if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.STOP){ break;}

        switch(schemeField.id){
          
              case 1:
              if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.STRUCT){
              com.isuwang.dapeng.json.demo.domain.PageRequest elem0 = new com.isuwang.dapeng.json.demo.domain.PageRequest();
        elem0=new com.isuwang.dapeng.json.demo.domain.serializer.PageRequestSerializer().read(iprot);
       bean.setPageRequest(Optional.of(elem0));
            }else{
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 2:
              if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.I32){
               int elem0 = iprot.readI32();
       bean.setHospitalId(Optional.of(elem0));
            }else{
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 3:
              if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.I32){
               int elem0 = iprot.readI32();
       bean.setLevel(Optional.of(elem0));
            }else{
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
              case 4:
              if(schemeField.type == com.isuwang.org.apache.thrift.protocol.TType.I32){
              com.isuwang.dapeng.json.demo.enums.AppointmentType elem0 = com.isuwang.dapeng.json.demo.enums.AppointmentType.findByValue(iprot.readI32());
       bean.setAppointmentType(Optional.of(elem0));
            }else{
              com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
              break;
            
          
            default:
            com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      validate(bean);
      return bean;
    }
    
      @Override
      public void write(com.isuwang.dapeng.json.demo.domain.ListPriceRuleRequest bean, TProtocol oprot) throws TException{

      validate(bean);
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("ListPriceRuleRequest"));

      if(bean.getPageRequest().isPresent()){
              oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("pageRequest", com.isuwang.org.apache.thrift.protocol.TType.STRUCT, (short) 1));
              com.isuwang.dapeng.json.demo.domain.PageRequest elem0 = bean.getPageRequest().get();
               new com.isuwang.dapeng.json.demo.domain.serializer.PageRequestSerializer().write(elem0, oprot);
              
            }
            if(bean.getHospitalId().isPresent()){
              oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("hospitalId", com.isuwang.org.apache.thrift.protocol.TType.I32, (short) 2));
              Integer elem1 = bean.getHospitalId().get();
              oprot.writeI32(elem1);
              
            }
            if(bean.getLevel().isPresent()){
              oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("level", com.isuwang.org.apache.thrift.protocol.TType.I32, (short) 3));
              Integer elem2 = bean.getLevel().get();
              oprot.writeI32(elem2);
              
            }
            if(bean.getAppointmentType().isPresent()){
              oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("appointmentType", com.isuwang.org.apache.thrift.protocol.TType.I32, (short) 4));
              com.isuwang.dapeng.json.demo.enums.AppointmentType elem3 = bean.getAppointmentType().get();
              oprot.writeI32(elem3.getValue());
              
            }
            
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }
    
      public void validate(com.isuwang.dapeng.json.demo.domain.ListPriceRuleRequest bean) throws TException{
      
                if(bean.getPageRequest().isPresent())
                new com.isuwang.dapeng.json.demo.domain.serializer.PageRequestSerializer().validate(bean.getPageRequest().get());
              
    }
    
        @Override
        public String toString(com.isuwang.dapeng.json.demo.domain.ListPriceRuleRequest bean)
        {return bean == null ? "null" : bean.toString();}
      }
      

      