package com.isuwang.dapeng.json.demo.enums;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        public enum QueryAppointmentFromEnum implements com.isuwang.org.apache.thrift.TEnum{
        
            /**
            *

 来自医生端

            **/
            DOCTOR(1),
          
            /**
            *

 来自病人端端

            **/
            PATIENT(2),
          
            /**
            *

 来自管理系统

            **/
            OSS(3);
          

        private final int value;

        private QueryAppointmentFromEnum(int value){
            this.value = value;
        }

        public int getValue(){
            return this.value;
        }

        public static QueryAppointmentFromEnum findByValue(int value){
            switch(value){
            
                 case 1:
                    return DOCTOR;
               
                 case 2:
                    return PATIENT;
               
                 case 3:
                    return OSS;
               
               default:
                   return null;
            }
        }
        }
      