package com.isuwang.dapeng.json.demo.enums;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

 推荐类型

        **/
        public enum RecommendTypeEnum implements com.isuwang.org.apache.thrift.TEnum{
        
            /**
            *

 量表推荐

            **/
            REC_TABLE(1),
          
            /**
            *

 心理治疗师医生推荐

            **/
            REC_DOCTOR(2);
          

        private final int value;

        private RecommendTypeEnum(int value){
            this.value = value;
        }

        public int getValue(){
            return this.value;
        }

        public static RecommendTypeEnum findByValue(int value){
            switch(value){
            
                 case 1:
                    return REC_TABLE;
               
                 case 2:
                    return REC_DOCTOR;
               
               default:
                   return null;
            }
        }
        }
      