package com.isuwang.dapeng.json.demo.enums;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

优惠券类型

        **/
        public enum TCouponType implements com.isuwang.org.apache.thrift.TEnum{
        
            /**
            *

优惠券

            **/
            DISCOUNT(1),
          
            /**
            *

心理咨询优惠券[仅限于预约心理咨询]

            **/
            APPOINTMENT(2);
          

        private final int value;

        private TCouponType(int value){
            this.value = value;
        }

        public int getValue(){
            return this.value;
        }

        public static TCouponType findByValue(int value){
            switch(value){
            
                 case 1:
                    return DISCOUNT;
               
                 case 2:
                    return APPOINTMENT;
               
               default:
                   return null;
            }
        }
        }
      