package com.isuwang.dapeng.json.demo.enums;

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 

  时段：早上、下午、晚上

        **/
        public enum TimeInterval implements com.isuwang.org.apache.thrift.TEnum{
        
            /**
            *

 早上

            **/
            MORNING(1),
          
            /**
            *

 下午

            **/
            AFTERNOON(2),
          
            /**
            *

 晚上

            **/
            NIGHT(3);
          

        private final int value;

        private TimeInterval(int value){
            this.value = value;
        }

        public int getValue(){
            return this.value;
        }

        public static TimeInterval findByValue(int value){
            switch(value){
            
                 case 1:
                    return MORNING;
               
                 case 2:
                    return AFTERNOON;
               
                 case 3:
                    return NIGHT;
               
               default:
                   return null;
            }
        }
        }
      