
        package com.isuwang.soa.order.scala.service

        import com.isuwang.dapeng.core.{Processor, Service}
        import com.isuwang.dapeng.core.SoaGlobalTransactional

        /**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        * 
        **/
        @Service(name ="com.isuwang.soa.order.service.OrderService" , version = "1.0.0")
        @Processor(className = "com.isuwang.soa.order.scala.OrderServiceCodec$Processor")
        trait OrderService {
        
            /**
            * 
            **/
            
            @throws[com.isuwang.dapeng.core.SoaException]
            def createOrder(
            order: com.isuwang.soa.order.scala.domain.Order ): Unit

          
            /**
            * 
            **/
            
            @throws[com.isuwang.dapeng.core.SoaException]
            def getOrderById(
            orderId: Int ): com.isuwang.soa.order.scala.domain.Order

          
        }
        