
      package com.isuwang.soa.order.service;

      import com.isuwang.dapeng.core.Processor;
      import com.isuwang.dapeng.core.Service;
      import com.isuwang.dapeng.core.SoaGlobalTransactional;

      /**
       * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

      * 
      **/
      @Service(name="com.isuwang.soa.order.service.OrderService",version = "1.0.0")
      @Processor(className = "com.isuwang.soa.order.OrderServiceCodec$Processor")
      public interface OrderService {
      
          /**
          * 
          **/
          
             
             void createOrder( com.isuwang.soa.order.domain.Order order) throws com.isuwang.dapeng.core.SoaException;
            
        
          /**
          * 
          **/
          
             
             com.isuwang.soa.order.domain.Order getOrderById( Integer orderId) throws com.isuwang.dapeng.core.SoaException;
            
        
      }
      