
package com.isuwang.soa.user.service;

import com.isuwang.dapeng.core.Processor;
import com.isuwang.dapeng.core.Service;
import com.isuwang.dapeng.core.SoaGlobalTransactional;

/**
 * Autogenerated by Dapeng-Code-Generator (1.2.2)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 **/
@Service(name = "com.isuwang.soa.user.service.UserService", version = "1.0.0")
@Processor(className = "com.isuwang.soa.user.UserServiceCodec$Processor")
public interface UserService {

    /**
     *
     **/


    void createUser(com.isuwang.soa.user.domain.User user) throws com.isuwang.dapeng.core.SoaException;


    /**
     *
     **/


    com.isuwang.soa.user.domain.User getUserById(Integer userId) throws com.isuwang.dapeng.core.SoaException;


}
      