
package com.isuwang.soa.user.service;

import com.isuwang.dapeng.core.Processor;
import com.isuwang.dapeng.core.Service;
import com.isuwang.dapeng.core.SoaGlobalTransactional;

import java.util.concurrent.Future;

/**
 * Autogenerated by Dapeng-Code-Generator (1.2.2)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 **/
@Service(name = "com.isuwang.soa.user.service.UserService", version = "1.0.0")
@Processor(className = "com.isuwang.soa.user.UserServiceAsyncCodec$Processor")
public interface UserServiceAsync extends com.isuwang.dapeng.core.definition.AsyncService {

    /**
     *
     **/


    Future<Void> createUser(com.isuwang.soa.user.domain.User user, long timeout) throws com.isuwang.dapeng.core.SoaException;


    /**
     *
     **/


    Future<com.isuwang.soa.user.domain.User> getUserById(Integer userId, long timeout) throws com.isuwang.dapeng.core.SoaException;


}
      